//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "alternative_release")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub gid: Uuid,
    pub release: i32,
    pub name: Option<String>,
    pub artist_credit: Option<i32>,
    pub r#type: i32,
    pub language: i32,
    pub script: i32,
    pub comment: String,
}



impl ActiveModelBehavior for ActiveModel {}
