//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "alternative_medium_track")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub alternative_medium: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub track: i32,
    pub alternative_track: i32,
}

impl ActiveModelBehavior for ActiveModel {}
