//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "alternative_track")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: Option<String>,
    pub artist_credit: Option<i32>,
    pub ref_count: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::alternative_medium_track::Entity")]
    AlternativeMediumTrack,
    #[sea_orm(
        belongs_to = "super::artist_credit::Entity",
        from = "Column::ArtistCredit",
        to = "super::artist_credit::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ArtistCredit,
}

impl Related<super::alternative_medium_track::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlternativeMediumTrack.def()
    }
}

impl Related<super::artist_credit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtistCredit.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::alternative_medium_track::Entity")]
    AlternativeMediumTrack,
    #[sea_orm(entity = "super::artist_credit::Entity")]
    ArtistCredit,
}
