//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "alternative_medium")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub medium: i32,
    pub alternative_release: i32,
    pub name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::alternative_medium_track::Entity")]
    AlternativeMediumTrack,
    #[sea_orm(
        belongs_to = "super::alternative_release::Entity",
        from = "Column::AlternativeRelease",
        to = "super::alternative_release::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AlternativeRelease,
    #[sea_orm(
        belongs_to = "super::medium::Entity",
        from = "Column::Medium",
        to = "super::medium::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Medium,
}

impl Related<super::alternative_medium_track::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlternativeMediumTrack.def()
    }
}

impl Related<super::alternative_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlternativeRelease.def()
    }
}

impl Related<super::medium::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Medium.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::alternative_medium_track::Entity")]
    AlternativeMediumTrack,
    #[sea_orm(entity = "super::alternative_release::Entity")]
    AlternativeRelease,
    #[sea_orm(entity = "super::medium::Entity")]
    Medium,
}
