//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "alternative_medium_track")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub alternative_medium: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub track: i32,
    pub alternative_track: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::alternative_medium::Entity",
        from = "Column::AlternativeMedium",
        to = "super::alternative_medium::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AlternativeMedium,
    #[sea_orm(
        belongs_to = "super::alternative_track::Entity",
        from = "Column::AlternativeTrack",
        to = "super::alternative_track::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AlternativeTrack,
    #[sea_orm(
        belongs_to = "super::track::Entity",
        from = "Column::Track",
        to = "super::track::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Track,
}

impl Related<super::alternative_medium::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlternativeMedium.def()
    }
}

impl Related<super::alternative_track::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlternativeTrack.def()
    }
}

impl Related<super::track::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Track.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::alternative_medium::Entity")]
    AlternativeMedium,
    #[sea_orm(entity = "super::alternative_track::Entity")]
    AlternativeTrack,
    #[sea_orm(entity = "super::track::Entity")]
    Track,
}
