//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "annotation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub editor: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub text: Option<String>,
    pub changelog: Option<String>,
    pub created: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::area_annotation::Entity")]
    AreaAnnotation,
    #[sea_orm(has_many = "super::artist_annotation::Entity")]
    ArtistAnnotation,
    #[sea_orm(
        belongs_to = "super::editor::Entity",
        from = "Column::Editor",
        to = "super::editor::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Editor,
    #[sea_orm(has_many = "super::event_annotation::Entity")]
    EventAnnotation,
    #[sea_orm(has_many = "super::genre_annotation::Entity")]
    GenreAnnotation,
    #[sea_orm(has_many = "super::instrument_annotation::Entity")]
    InstrumentAnnotation,
    #[sea_orm(has_many = "super::label_annotation::Entity")]
    LabelAnnotation,
    #[sea_orm(has_many = "super::mood_annotation::Entity")]
    MoodAnnotation,
    #[sea_orm(has_many = "super::place_annotation::Entity")]
    PlaceAnnotation,
    #[sea_orm(has_many = "super::recording_annotation::Entity")]
    RecordingAnnotation,
    #[sea_orm(has_many = "super::release_annotation::Entity")]
    ReleaseAnnotation,
    #[sea_orm(has_many = "super::release_group_annotation::Entity")]
    ReleaseGroupAnnotation,
    #[sea_orm(has_many = "super::series_annotation::Entity")]
    SeriesAnnotation,
    #[sea_orm(has_many = "super::work_annotation::Entity")]
    WorkAnnotation,
}

impl Related<super::area_annotation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AreaAnnotation.def()
    }
}

impl Related<super::artist_annotation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtistAnnotation.def()
    }
}

impl Related<super::editor::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Editor.def()
    }
}

impl Related<super::event_annotation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventAnnotation.def()
    }
}

impl Related<super::genre_annotation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GenreAnnotation.def()
    }
}

impl Related<super::instrument_annotation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InstrumentAnnotation.def()
    }
}

impl Related<super::label_annotation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LabelAnnotation.def()
    }
}

impl Related<super::mood_annotation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MoodAnnotation.def()
    }
}

impl Related<super::place_annotation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlaceAnnotation.def()
    }
}

impl Related<super::recording_annotation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecordingAnnotation.def()
    }
}

impl Related<super::release_annotation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseAnnotation.def()
    }
}

impl Related<super::release_group_annotation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseGroupAnnotation.def()
    }
}

impl Related<super::series_annotation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SeriesAnnotation.def()
    }
}

impl Related<super::work_annotation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkAnnotation.def()
    }
}

impl Related<super::area::Entity> for Entity {
    fn to() -> RelationDef {
        super::area_annotation::Relation::Area.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::area_annotation::Relation::Annotation.def().rev())
    }
}

impl Related<super::artist::Entity> for Entity {
    fn to() -> RelationDef {
        super::artist_annotation::Relation::Artist.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::artist_annotation::Relation::Annotation.def().rev())
    }
}

impl Related<super::event::Entity> for Entity {
    fn to() -> RelationDef {
        super::event_annotation::Relation::Event.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::event_annotation::Relation::Annotation.def().rev())
    }
}

impl Related<super::genre::Entity> for Entity {
    fn to() -> RelationDef {
        super::genre_annotation::Relation::Genre.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::genre_annotation::Relation::Annotation.def().rev())
    }
}

impl Related<super::instrument::Entity> for Entity {
    fn to() -> RelationDef {
        super::instrument_annotation::Relation::Instrument.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::instrument_annotation::Relation::Annotation
                .def()
                .rev(),
        )
    }
}

impl Related<super::label::Entity> for Entity {
    fn to() -> RelationDef {
        super::label_annotation::Relation::Label.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::label_annotation::Relation::Annotation.def().rev())
    }
}

impl Related<super::mood::Entity> for Entity {
    fn to() -> RelationDef {
        super::mood_annotation::Relation::Mood.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::mood_annotation::Relation::Annotation.def().rev())
    }
}

impl Related<super::place::Entity> for Entity {
    fn to() -> RelationDef {
        super::place_annotation::Relation::Place.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::place_annotation::Relation::Annotation.def().rev())
    }
}

impl Related<super::recording::Entity> for Entity {
    fn to() -> RelationDef {
        super::recording_annotation::Relation::Recording.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::recording_annotation::Relation::Annotation
                .def()
                .rev(),
        )
    }
}

impl Related<super::release::Entity> for Entity {
    fn to() -> RelationDef {
        super::release_annotation::Relation::Release.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::release_annotation::Relation::Annotation.def().rev())
    }
}

impl Related<super::release_group::Entity> for Entity {
    fn to() -> RelationDef {
        super::release_group_annotation::Relation::ReleaseGroup.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::release_group_annotation::Relation::Annotation
                .def()
                .rev(),
        )
    }
}

impl Related<super::series::Entity> for Entity {
    fn to() -> RelationDef {
        super::series_annotation::Relation::Series.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::series_annotation::Relation::Annotation.def().rev())
    }
}

impl Related<super::work::Entity> for Entity {
    fn to() -> RelationDef {
        super::work_annotation::Relation::Work.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::work_annotation::Relation::Annotation.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::area_annotation::Entity")]
    AreaAnnotation,
    #[sea_orm(entity = "super::artist_annotation::Entity")]
    ArtistAnnotation,
    #[sea_orm(entity = "super::editor::Entity")]
    Editor,
    #[sea_orm(entity = "super::event_annotation::Entity")]
    EventAnnotation,
    #[sea_orm(entity = "super::genre_annotation::Entity")]
    GenreAnnotation,
    #[sea_orm(entity = "super::instrument_annotation::Entity")]
    InstrumentAnnotation,
    #[sea_orm(entity = "super::label_annotation::Entity")]
    LabelAnnotation,
    #[sea_orm(entity = "super::mood_annotation::Entity")]
    MoodAnnotation,
    #[sea_orm(entity = "super::place_annotation::Entity")]
    PlaceAnnotation,
    #[sea_orm(entity = "super::recording_annotation::Entity")]
    RecordingAnnotation,
    #[sea_orm(entity = "super::release_annotation::Entity")]
    ReleaseAnnotation,
    #[sea_orm(entity = "super::release_group_annotation::Entity")]
    ReleaseGroupAnnotation,
    #[sea_orm(entity = "super::series_annotation::Entity")]
    SeriesAnnotation,
    #[sea_orm(entity = "super::work_annotation::Entity")]
    WorkAnnotation,
    #[sea_orm(entity = "super::area::Entity")]
    Area,
    #[sea_orm(entity = "super::artist::Entity")]
    Artist,
    #[sea_orm(entity = "super::event::Entity")]
    Event,
    #[sea_orm(entity = "super::genre::Entity")]
    Genre,
    #[sea_orm(entity = "super::instrument::Entity")]
    Instrument,
    #[sea_orm(entity = "super::label::Entity")]
    Label,
    #[sea_orm(entity = "super::mood::Entity")]
    Mood,
    #[sea_orm(entity = "super::place::Entity")]
    Place,
    #[sea_orm(entity = "super::recording::Entity")]
    Recording,
    #[sea_orm(entity = "super::release::Entity")]
    Release,
    #[sea_orm(entity = "super::release_group::Entity")]
    ReleaseGroup,
    #[sea_orm(entity = "super::series::Entity")]
    Series,
    #[sea_orm(entity = "super::work::Entity")]
    Work,
}
