//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "application")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub owner: i32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", unique)]
    pub oauth_id: String,
    #[sea_orm(column_type = "Text")]
    pub oauth_secret: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub oauth_redirect_uri: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::editor::Entity",
        from = "Column::Owner",
        to = "super::editor::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Editor,
    #[sea_orm(has_many = "super::editor_oauth_token::Entity")]
    EditorOauthToken,
}

impl Related<super::editor::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Editor.def()
    }
}

impl Related<super::editor_oauth_token::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditorOauthToken.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::editor::Entity")]
    Editor,
    #[sea_orm(entity = "super::editor_oauth_token::Entity")]
    EditorOauthToken,
}
