//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "area_tag")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub area: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub tag: i32,
    pub count: i32,
    pub last_updated: Option<DateTimeWithTimeZone>,
}


#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
