//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "area_attribute")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub area: i32,
    pub area_attribute_type: i32,
    pub area_attribute_type_allowed_value: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub area_attribute_text: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::area::Entity",
        from = "Column::Area",
        to = "super::area::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Area,
    #[sea_orm(
        belongs_to = "super::area_attribute_type::Entity",
        from = "Column::AreaAttributeType",
        to = "super::area_attribute_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AreaAttributeType,
    #[sea_orm(
        belongs_to = "super::area_attribute_type_allowed_value::Entity",
        from = "Column::AreaAttributeTypeAllowedValue",
        to = "super::area_attribute_type_allowed_value::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AreaAttributeTypeAllowedValue,
}

impl Related<super::area::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Area.def()
    }
}

impl Related<super::area_attribute_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AreaAttributeType.def()
    }
}

impl Related<super::area_attribute_type_allowed_value::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AreaAttributeTypeAllowedValue.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::area::Entity")]
    Area,
    #[sea_orm(entity = "super::area_attribute_type::Entity")]
    AreaAttributeType,
    #[sea_orm(entity = "super::area_attribute_type_allowed_value::Entity")]
    AreaAttributeTypeAllowedValue,
}
