//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "area")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub gid: Uuid,
    pub name: String,
    pub r#type: Option<i32>,
    pub edits_pending: i32,
    pub last_updated: Option<DateTimeWithTimeZone>,
    pub begin_date_year: Option<i16>,
    pub begin_date_month: Option<i16>,
    pub begin_date_day: Option<i16>,
    pub end_date_year: Option<i16>,
    pub end_date_month: Option<i16>,
    pub end_date_day: Option<i16>,
    pub ended: bool,
    pub comment: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::area_alias::Entity")]
    AreaAlias,
    #[sea_orm(has_many = "super::area_annotation::Entity")]
    AreaAnnotation,
    #[sea_orm(has_many = "super::area_attribute::Entity")]
    AreaAttribute,
    #[sea_orm(has_many = "super::area_gid_redirect::Entity")]
    AreaGidRedirect,
    #[sea_orm(has_many = "super::area_tag::Entity")]
    AreaTag,
    #[sea_orm(has_many = "super::area_tag_raw::Entity")]
    AreaTagRaw,
    #[sea_orm(
        belongs_to = "super::area_type::Entity",
        from = "Column::Type",
        to = "super::area_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AreaType,
    #[sea_orm(has_one = "super::country_area::Entity")]
    CountryArea,
    #[sea_orm(has_many = "super::edit_area::Entity")]
    EditArea,
    #[sea_orm(has_many = "super::editor::Entity")]
    Editor,
    #[sea_orm(has_many = "super::editor_collection_area::Entity")]
    EditorCollectionArea,
    #[sea_orm(has_many = "super::iso_3166_1::Entity")]
    Iso31661,
    #[sea_orm(has_many = "super::iso_3166_2::Entity")]
    Iso31662,
    #[sea_orm(has_many = "super::iso_3166_3::Entity")]
    Iso31663,
    #[sea_orm(has_many = "super::l_area_artist::Entity")]
    LAreaArtist,
    #[sea_orm(has_many = "super::l_area_event::Entity")]
    LAreaEvent,
    #[sea_orm(has_many = "super::l_area_genre::Entity")]
    LAreaGenre,
    #[sea_orm(has_many = "super::l_area_instrument::Entity")]
    LAreaInstrument,
    #[sea_orm(has_many = "super::l_area_label::Entity")]
    LAreaLabel,
    #[sea_orm(has_many = "super::l_area_mood::Entity")]
    LAreaMood,
    #[sea_orm(has_many = "super::l_area_place::Entity")]
    LAreaPlace,
    #[sea_orm(has_many = "super::l_area_recording::Entity")]
    LAreaRecording,
    #[sea_orm(has_many = "super::l_area_release::Entity")]
    LAreaRelease,
    #[sea_orm(has_many = "super::l_area_release_group::Entity")]
    LAreaReleaseGroup,
    #[sea_orm(has_many = "super::l_area_series::Entity")]
    LAreaSeries,
    #[sea_orm(has_many = "super::l_area_url::Entity")]
    LAreaUrl,
    #[sea_orm(has_many = "super::l_area_work::Entity")]
    LAreaWork,
    #[sea_orm(has_many = "super::label::Entity")]
    Label,
    #[sea_orm(has_many = "super::place::Entity")]
    Place,
}

impl Related<super::area_alias::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AreaAlias.def()
    }
}

impl Related<super::area_annotation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AreaAnnotation.def()
    }
}

impl Related<super::area_attribute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AreaAttribute.def()
    }
}

impl Related<super::area_gid_redirect::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AreaGidRedirect.def()
    }
}

impl Related<super::area_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AreaTag.def()
    }
}

impl Related<super::area_tag_raw::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AreaTagRaw.def()
    }
}

impl Related<super::area_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AreaType.def()
    }
}

impl Related<super::country_area::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CountryArea.def()
    }
}

impl Related<super::edit_area::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditArea.def()
    }
}

impl Related<super::editor::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Editor.def()
    }
}

impl Related<super::editor_collection_area::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditorCollectionArea.def()
    }
}

impl Related<super::iso_3166_1::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Iso31661.def()
    }
}

impl Related<super::iso_3166_2::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Iso31662.def()
    }
}

impl Related<super::iso_3166_3::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Iso31663.def()
    }
}

impl Related<super::l_area_artist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaArtist.def()
    }
}

impl Related<super::l_area_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaEvent.def()
    }
}

impl Related<super::l_area_genre::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaGenre.def()
    }
}

impl Related<super::l_area_instrument::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaInstrument.def()
    }
}

impl Related<super::l_area_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaLabel.def()
    }
}

impl Related<super::l_area_mood::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaMood.def()
    }
}

impl Related<super::l_area_place::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaPlace.def()
    }
}

impl Related<super::l_area_recording::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaRecording.def()
    }
}

impl Related<super::l_area_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaRelease.def()
    }
}

impl Related<super::l_area_release_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaReleaseGroup.def()
    }
}

impl Related<super::l_area_series::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaSeries.def()
    }
}

impl Related<super::l_area_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaUrl.def()
    }
}

impl Related<super::l_area_work::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaWork.def()
    }
}

impl Related<super::label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Label.def()
    }
}

impl Related<super::place::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Place.def()
    }
}

impl Related<super::annotation::Entity> for Entity {
    fn to() -> RelationDef {
        super::area_annotation::Relation::Annotation.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::area_annotation::Relation::Area.def().rev())
    }
}

impl Related<super::edit::Entity> for Entity {
    fn to() -> RelationDef {
        super::edit_area::Relation::Edit.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::edit_area::Relation::Area.def().rev())
    }
}

impl Related<super::editor_collection::Entity> for Entity {
    fn to() -> RelationDef {
        super::editor_collection_area::Relation::EditorCollection.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::editor_collection_area::Relation::Area.def().rev())
    }
}

impl Related<super::tag::Entity> for Entity {
    fn to() -> RelationDef {
        super::area_tag::Relation::Tag.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::area_tag::Relation::Area.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::area_alias::Entity")]
    AreaAlias,
    #[sea_orm(entity = "super::area_annotation::Entity")]
    AreaAnnotation,
    #[sea_orm(entity = "super::area_attribute::Entity")]
    AreaAttribute,
    #[sea_orm(entity = "super::area_gid_redirect::Entity")]
    AreaGidRedirect,
    #[sea_orm(entity = "super::area_tag::Entity")]
    AreaTag,
    #[sea_orm(entity = "super::area_tag_raw::Entity")]
    AreaTagRaw,
    #[sea_orm(entity = "super::area_type::Entity")]
    AreaType,
    #[sea_orm(entity = "super::country_area::Entity")]
    CountryArea,
    #[sea_orm(entity = "super::edit_area::Entity")]
    EditArea,
    #[sea_orm(entity = "super::editor::Entity")]
    Editor,
    #[sea_orm(entity = "super::editor_collection_area::Entity")]
    EditorCollectionArea,
    #[sea_orm(entity = "super::iso_3166_1::Entity")]
    Iso31661,
    #[sea_orm(entity = "super::iso_3166_2::Entity")]
    Iso31662,
    #[sea_orm(entity = "super::iso_3166_3::Entity")]
    Iso31663,
    #[sea_orm(entity = "super::l_area_artist::Entity")]
    LAreaArtist,
    #[sea_orm(entity = "super::l_area_event::Entity")]
    LAreaEvent,
    #[sea_orm(entity = "super::l_area_genre::Entity")]
    LAreaGenre,
    #[sea_orm(entity = "super::l_area_instrument::Entity")]
    LAreaInstrument,
    #[sea_orm(entity = "super::l_area_label::Entity")]
    LAreaLabel,
    #[sea_orm(entity = "super::l_area_mood::Entity")]
    LAreaMood,
    #[sea_orm(entity = "super::l_area_place::Entity")]
    LAreaPlace,
    #[sea_orm(entity = "super::l_area_recording::Entity")]
    LAreaRecording,
    #[sea_orm(entity = "super::l_area_release::Entity")]
    LAreaRelease,
    #[sea_orm(entity = "super::l_area_release_group::Entity")]
    LAreaReleaseGroup,
    #[sea_orm(entity = "super::l_area_series::Entity")]
    LAreaSeries,
    #[sea_orm(entity = "super::l_area_url::Entity")]
    LAreaUrl,
    #[sea_orm(entity = "super::l_area_work::Entity")]
    LAreaWork,
    #[sea_orm(entity = "super::label::Entity")]
    Label,
    #[sea_orm(entity = "super::place::Entity")]
    Place,
    #[sea_orm(entity = "super::annotation::Entity")]
    Annotation,
    #[sea_orm(entity = "super::edit::Entity")]
    Edit,
    #[sea_orm(entity = "super::editor_collection::Entity")]
    EditorCollection,
    #[sea_orm(entity = "super::tag::Entity")]
    Tag,
}
