//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "artist_release")]
pub struct Model {
    pub is_track_artist: bool,
    pub artist: i32,
    pub first_release_date: Option<i32>,
    pub catalog_numbers: Option<Vec<String>>,
    pub country_code: Option<String>,
    pub barcode: Option<i64>,
    pub name: String,
    pub release: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::artist::Entity",
        from = "(Column::Artist, Column::Artist)",
        to = "(super::artist::Column::Id, super::artist::Column::Id)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Artist,
    #[sea_orm(
        belongs_to = "super::release::Entity",
        from = "(Column::Release, Column::Release)",
        to = "(super::release::Column::Id, super::release::Column::Id)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Release,
}

impl Related<super::artist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Artist.def()
    }
}

impl Related<super::release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Release.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::artist::Entity")]
    Artist,
    #[sea_orm(entity = "super::release::Entity")]
    Release,
}
