//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "artist_credit")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub artist_count: i16,
    pub ref_count: Option<i32>,
    pub created: Option<DateTimeWithTimeZone>,
    pub edits_pending: i32,
    #[sea_orm(unique)]
    pub gid: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::alternative_release::Entity")]
    AlternativeRelease,
    #[sea_orm(has_many = "super::alternative_track::Entity")]
    AlternativeTrack,
    #[sea_orm(has_many = "super::artist_credit_gid_redirect::Entity")]
    ArtistCreditGidRedirect,
    #[sea_orm(has_many = "super::artist_credit_name::Entity")]
    ArtistCreditName,
    #[sea_orm(has_many = "super::recording::Entity")]
    Recording,
    #[sea_orm(has_many = "super::release::Entity")]
    Release,
    #[sea_orm(has_many = "super::release_group::Entity")]
    ReleaseGroup,
    #[sea_orm(has_many = "super::track::Entity")]
    Track,
}

impl Related<super::alternative_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlternativeRelease.def()
    }
}

impl Related<super::alternative_track::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlternativeTrack.def()
    }
}

impl Related<super::artist_credit_gid_redirect::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtistCreditGidRedirect.def()
    }
}

impl Related<super::artist_credit_name::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtistCreditName.def()
    }
}

impl Related<super::recording::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Recording.def()
    }
}

impl Related<super::release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Release.def()
    }
}

impl Related<super::release_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseGroup.def()
    }
}

impl Related<super::track::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Track.def()
    }
}

impl Related<super::artist::Entity> for Entity {
    fn to() -> RelationDef {
        super::artist_credit_name::Relation::Artist.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::artist_credit_name::Relation::ArtistCredit
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::alternative_release::Entity")]
    AlternativeRelease,
    #[sea_orm(entity = "super::alternative_track::Entity")]
    AlternativeTrack,
    #[sea_orm(entity = "super::artist_credit_gid_redirect::Entity")]
    ArtistCreditGidRedirect,
    #[sea_orm(entity = "super::artist_credit_name::Entity")]
    ArtistCreditName,
    #[sea_orm(entity = "super::recording::Entity")]
    Recording,
    #[sea_orm(entity = "super::release::Entity")]
    Release,
    #[sea_orm(entity = "super::release_group::Entity")]
    ReleaseGroup,
    #[sea_orm(entity = "super::track::Entity")]
    Track,
    #[sea_orm(entity = "super::artist::Entity")]
    Artist,
}
