//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "artist_annotation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub artist: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub annotation: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::annotation::Entity",
        from = "Column::Annotation",
        to = "super::annotation::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Annotation,
    #[sea_orm(
        belongs_to = "super::artist::Entity",
        from = "Column::Artist",
        to = "super::artist::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Artist,
}

impl Related<super::annotation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Annotation.def()
    }
}

impl Related<super::artist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Artist.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::annotation::Entity")]
    Annotation,
    #[sea_orm(entity = "super::artist::Entity")]
    Artist,
}
