//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "artist")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub gid: Uuid,
    #[sea_orm(unique)]
    pub name: String,
    pub sort_name: String,
    pub begin_date_year: Option<i16>,
    pub begin_date_month: Option<i16>,
    pub begin_date_day: Option<i16>,
    pub end_date_year: Option<i16>,
    pub end_date_month: Option<i16>,
    pub end_date_day: Option<i16>,
    pub r#type: Option<i32>,
    pub area: Option<i32>,
    pub gender: Option<i32>,
    pub comment: String,
    pub edits_pending: i32,
    pub last_updated: Option<DateTimeWithTimeZone>,
    pub ended: bool,
    pub begin_area: Option<i32>,
    pub end_area: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::area::Entity",
        from = "Column::Area",
        to = "super::area::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Area3,
    #[sea_orm(
        belongs_to = "super::area::Entity",
        from = "Column::BeginArea",
        to = "super::area::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Area2,
    #[sea_orm(
        belongs_to = "super::area::Entity",
        from = "Column::EndArea",
        to = "super::area::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Area1,
    #[sea_orm(has_many = "super::artist_alias::Entity")]
    ArtistAlias,
    #[sea_orm(has_many = "super::artist_annotation::Entity")]
    ArtistAnnotation,
    #[sea_orm(has_many = "super::artist_attribute::Entity")]
    ArtistAttribute,
    #[sea_orm(has_many = "super::artist_credit_name::Entity")]
    ArtistCreditName,
    #[sea_orm(has_many = "super::artist_gid_redirect::Entity")]
    ArtistGidRedirect,
    #[sea_orm(has_many = "super::artist_ipi::Entity")]
    ArtistIpi,
    #[sea_orm(has_many = "super::artist_isni::Entity")]
    ArtistIsni,
    #[sea_orm(has_one = "super::artist_meta::Entity")]
    ArtistMeta,
    #[sea_orm(has_many = "super::artist_rating_raw::Entity")]
    ArtistRatingRaw,
    #[sea_orm(has_many = "super::artist_tag::Entity")]
    ArtistTag,
    #[sea_orm(has_many = "super::artist_tag_raw::Entity")]
    ArtistTagRaw,
    #[sea_orm(
        belongs_to = "super::artist_type::Entity",
        from = "Column::Type",
        to = "super::artist_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ArtistType,
    #[sea_orm(has_many = "super::edit_artist::Entity")]
    EditArtist,
    #[sea_orm(has_many = "super::editor_collection_artist::Entity")]
    EditorCollectionArtist,
    #[sea_orm(has_many = "super::editor_subscribe_artist::Entity")]
    EditorSubscribeArtist,
    #[sea_orm(
        belongs_to = "super::gender::Entity",
        from = "Column::Gender",
        to = "super::gender::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Gender,
    #[sea_orm(has_many = "super::l_area_artist::Entity")]
    LAreaArtist,
    #[sea_orm(has_many = "super::l_artist_event::Entity")]
    LArtistEvent,
    #[sea_orm(has_many = "super::l_artist_genre::Entity")]
    LArtistGenre,
    #[sea_orm(has_many = "super::l_artist_instrument::Entity")]
    LArtistInstrument,
    #[sea_orm(has_many = "super::l_artist_label::Entity")]
    LArtistLabel,
    #[sea_orm(has_many = "super::l_artist_mood::Entity")]
    LArtistMood,
    #[sea_orm(has_many = "super::l_artist_place::Entity")]
    LArtistPlace,
    #[sea_orm(has_many = "super::l_artist_recording::Entity")]
    LArtistRecording,
    #[sea_orm(has_many = "super::l_artist_release::Entity")]
    LArtistRelease,
    #[sea_orm(has_many = "super::l_artist_release_group::Entity")]
    LArtistReleaseGroup,
    #[sea_orm(has_many = "super::l_artist_series::Entity")]
    LArtistSeries,
    #[sea_orm(has_many = "super::l_artist_url::Entity")]
    LArtistUrl,
    #[sea_orm(has_many = "super::l_artist_work::Entity")]
    LArtistWork,
}

impl Related<super::artist_alias::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtistAlias.def()
    }
}

impl Related<super::artist_annotation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtistAnnotation.def()
    }
}

impl Related<super::artist_attribute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtistAttribute.def()
    }
}

impl Related<super::artist_credit_name::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtistCreditName.def()
    }
}

impl Related<super::artist_gid_redirect::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtistGidRedirect.def()
    }
}

impl Related<super::artist_ipi::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtistIpi.def()
    }
}

impl Related<super::artist_isni::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtistIsni.def()
    }
}

impl Related<super::artist_meta::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtistMeta.def()
    }
}

impl Related<super::artist_rating_raw::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtistRatingRaw.def()
    }
}

impl Related<super::artist_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtistTag.def()
    }
}

impl Related<super::artist_tag_raw::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtistTagRaw.def()
    }
}

impl Related<super::artist_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtistType.def()
    }
}

impl Related<super::edit_artist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditArtist.def()
    }
}

impl Related<super::editor_collection_artist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditorCollectionArtist.def()
    }
}

impl Related<super::editor_subscribe_artist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditorSubscribeArtist.def()
    }
}

impl Related<super::gender::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Gender.def()
    }
}

impl Related<super::l_area_artist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaArtist.def()
    }
}

impl Related<super::l_artist_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistEvent.def()
    }
}

impl Related<super::l_artist_genre::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistGenre.def()
    }
}

impl Related<super::l_artist_instrument::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistInstrument.def()
    }
}

impl Related<super::l_artist_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistLabel.def()
    }
}

impl Related<super::l_artist_mood::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistMood.def()
    }
}

impl Related<super::l_artist_place::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistPlace.def()
    }
}

impl Related<super::l_artist_recording::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistRecording.def()
    }
}

impl Related<super::l_artist_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistRelease.def()
    }
}

impl Related<super::l_artist_release_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistReleaseGroup.def()
    }
}

impl Related<super::l_artist_series::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistSeries.def()
    }
}

impl Related<super::l_artist_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistUrl.def()
    }
}

impl Related<super::l_artist_work::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistWork.def()
    }
}

impl Related<super::annotation::Entity> for Entity {
    fn to() -> RelationDef {
        super::artist_annotation::Relation::Annotation.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::artist_annotation::Relation::Artist.def().rev())
    }
}

impl Related<super::artist_credit::Entity> for Entity {
    fn to() -> RelationDef {
        super::artist_credit_name::Relation::ArtistCredit.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::artist_credit_name::Relation::Artist.def().rev())
    }
}

impl Related<super::edit::Entity> for Entity {
    fn to() -> RelationDef {
        super::edit_artist::Relation::Edit.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::edit_artist::Relation::Artist.def().rev())
    }
}

impl Related<super::editor::Entity> for Entity {
    fn to() -> RelationDef {
        super::artist_rating_raw::Relation::Editor.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::artist_rating_raw::Relation::Artist.def().rev())
    }
}

impl Related<super::editor_collection::Entity> for Entity {
    fn to() -> RelationDef {
        super::editor_collection_artist::Relation::EditorCollection.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::editor_collection_artist::Relation::Artist
                .def()
                .rev(),
        )
    }
}

impl Related<super::tag::Entity> for Entity {
    fn to() -> RelationDef {
        super::artist_tag::Relation::Tag.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::artist_tag::Relation::Artist.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::area::Entity", def = "Relation::Area3.def()")]
    Area3,
    #[sea_orm(entity = "super::area::Entity", def = "Relation::Area2.def()")]
    Area2,
    #[sea_orm(entity = "super::area::Entity", def = "Relation::Area1.def()")]
    Area1,
    #[sea_orm(entity = "super::artist_alias::Entity")]
    ArtistAlias,
    #[sea_orm(entity = "super::artist_annotation::Entity")]
    ArtistAnnotation,
    #[sea_orm(entity = "super::artist_attribute::Entity")]
    ArtistAttribute,
    #[sea_orm(entity = "super::artist_credit_name::Entity")]
    ArtistCreditName,
    #[sea_orm(entity = "super::artist_gid_redirect::Entity")]
    ArtistGidRedirect,
    #[sea_orm(entity = "super::artist_ipi::Entity")]
    ArtistIpi,
    #[sea_orm(entity = "super::artist_isni::Entity")]
    ArtistIsni,
    #[sea_orm(entity = "super::artist_meta::Entity")]
    ArtistMeta,
    #[sea_orm(entity = "super::artist_rating_raw::Entity")]
    ArtistRatingRaw,
    #[sea_orm(entity = "super::artist_tag::Entity")]
    ArtistTag,
    #[sea_orm(entity = "super::artist_tag_raw::Entity")]
    ArtistTagRaw,
    #[sea_orm(entity = "super::artist_type::Entity")]
    ArtistType,
    #[sea_orm(entity = "super::edit_artist::Entity")]
    EditArtist,
    #[sea_orm(entity = "super::editor_collection_artist::Entity")]
    EditorCollectionArtist,
    #[sea_orm(entity = "super::editor_subscribe_artist::Entity")]
    EditorSubscribeArtist,
    #[sea_orm(entity = "super::gender::Entity")]
    Gender,
    #[sea_orm(entity = "super::l_area_artist::Entity")]
    LAreaArtist,
    #[sea_orm(entity = "super::l_artist_event::Entity")]
    LArtistEvent,
    #[sea_orm(entity = "super::l_artist_genre::Entity")]
    LArtistGenre,
    #[sea_orm(entity = "super::l_artist_instrument::Entity")]
    LArtistInstrument,
    #[sea_orm(entity = "super::l_artist_label::Entity")]
    LArtistLabel,
    #[sea_orm(entity = "super::l_artist_mood::Entity")]
    LArtistMood,
    #[sea_orm(entity = "super::l_artist_place::Entity")]
    LArtistPlace,
    #[sea_orm(entity = "super::l_artist_recording::Entity")]
    LArtistRecording,
    #[sea_orm(entity = "super::l_artist_release::Entity")]
    LArtistRelease,
    #[sea_orm(entity = "super::l_artist_release_group::Entity")]
    LArtistReleaseGroup,
    #[sea_orm(entity = "super::l_artist_series::Entity")]
    LArtistSeries,
    #[sea_orm(entity = "super::l_artist_url::Entity")]
    LArtistUrl,
    #[sea_orm(entity = "super::l_artist_work::Entity")]
    LArtistWork,
    #[sea_orm(entity = "super::annotation::Entity")]
    Annotation,
    #[sea_orm(entity = "super::artist_credit::Entity")]
    ArtistCredit,
    #[sea_orm(entity = "super::edit::Entity")]
    Edit,
    #[sea_orm(entity = "super::editor::Entity")]
    Editor,
    #[sea_orm(entity = "super::editor_collection::Entity")]
    EditorCollection,
    #[sea_orm(entity = "super::tag::Entity")]
    Tag,
}
