//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "artist_attribute_type")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub comment: String,
    pub free_text: bool,
    pub parent: Option<i32>,
    pub child_order: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(unique)]
    pub gid: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::artist_attribute::Entity")]
    ArtistAttribute,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::Parent",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::artist_attribute_type_allowed_value::Entity")]
    ArtistAttributeTypeAllowedValue,
}

impl Related<super::artist_attribute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtistAttribute.def()
    }
}

impl Related<super::artist_attribute_type_allowed_value::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtistAttributeTypeAllowedValue.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::artist_attribute::Entity")]
    ArtistAttribute,
    #[sea_orm(entity = "Entity", def = "Relation::SelfRef.def()")]
    SelfRef,
    #[sea_orm(entity = "super::artist_attribute_type_allowed_value::Entity")]
    ArtistAttributeTypeAllowedValue,
    #[sea_orm(entity = "Entity", def = "Relation::SelfRef.def().rev()")]
    SelfRefReverse,
}
