//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "artist_release_group")]
pub struct Model {
    pub is_track_artist: bool,
    pub artist: i32,
    pub unofficial: bool,
    pub primary_type_child_order: Option<i16>,
    pub primary_type: Option<i16>,
    pub secondary_type_child_orders: Option<Vec<i16>>,
    pub secondary_types: Option<Vec<i16>>,
    pub first_release_date: Option<i32>,
    pub name: String,
    pub release_group: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::artist::Entity",
        from = "(Column::Artist, Column::Artist)",
        to = "(super::artist::Column::Id, super::artist::Column::Id)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Artist,
    #[sea_orm(
        belongs_to = "super::release_group::Entity",
        from = "(Column::ReleaseGroup, Column::ReleaseGroup)",
        to = "(super::release_group::Column::Id, super::release_group::Column::Id)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ReleaseGroup,
}

impl Related<super::artist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Artist.def()
    }
}

impl Related<super::release_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseGroup.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::artist::Entity")]
    Artist,
    #[sea_orm(entity = "super::release_group::Entity")]
    ReleaseGroup,
}
