//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "artist_credit")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub artist_count: i16,
    pub ref_count: Option<i32>,
    pub created: Option<DateTimeWithTimeZone>,
    pub edits_pending: i32,
    #[sea_orm(unique)]
    pub gid: Uuid,
}


impl ActiveModelBehavior for ActiveModel {}
