//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "artist_alias")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(
        belongs_to,
        from = "artist",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction",
        unique_key = "artist_alias_idx_primary"
    )]
    pub artist: i32,
    pub name: String,
    #[sea_orm(
        column_type = "Text",
        nullable,
        unique_key = "artist_alias_idx_primary"
    )]
    pub locale: Option<String>,
    pub edits_pending: i32,
    pub last_updated: Option<DateTimeWithTimeZone>,
    pub r#type: Option<i32>,
    pub sort_name: String,
    pub begin_date_year: Option<i16>,
    pub begin_date_month: Option<i16>,
    pub begin_date_day: Option<i16>,
    pub end_date_year: Option<i16>,
    pub end_date_month: Option<i16>,
    pub end_date_day: Option<i16>,
    pub primary_for_locale: bool,
    pub ended: bool,
    #[sea_orm(
        belongs_to,
        from = "artist",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub artist: HasOne<super::artist::Entity>,
    #[sea_orm(
        belongs_to,
        from = "type",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub artist_alias_type: HasOne<super::artist_alias_type::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
