//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "autoeditor_election_vote")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub autoeditor_election: i32,
    pub voter: i32,
    pub vote: i32,
    pub vote_time: DateTimeWithTimeZone,
}


impl ActiveModelBehavior for ActiveModel {}
