//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "autoeditor_election_vote")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub autoeditor_election: i32,
    pub voter: i32,
    pub vote: i32,
    pub vote_time: DateTimeWithTimeZone,
}


#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
