//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "autoeditor_election")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub candidate: i32,
    pub proposer: i32,
    pub seconder_1: Option<i32>,
    pub seconder_2: Option<i32>,
    pub status: i32,
    pub yes_votes: i32,
    pub no_votes: i32,
    pub propose_time: DateTimeWithTimeZone,
    pub open_time: Option<DateTimeWithTimeZone>,
    pub close_time: Option<DateTimeWithTimeZone>,
}


#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
