//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "autoeditor_election")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub candidate: i32,
    pub proposer: i32,
    pub seconder_1: Option<i32>,
    pub seconder_2: Option<i32>,
    pub status: i32,
    pub yes_votes: i32,
    pub no_votes: i32,
    pub propose_time: DateTimeWithTimeZone,
    pub open_time: Option<DateTimeWithTimeZone>,
    pub close_time: Option<DateTimeWithTimeZone>,
    #[sea_orm(has_many)]
    pub autoeditor_election_votes: HasMany<super::autoeditor_election_vote::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Editor4",
        from = "candidate",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub editor_4: HasOne<super::editor::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Editor3",
        from = "proposer",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub editor_3: HasOne<super::editor::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Editor2",
        from = "seconder1",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub editor_2: HasOne<super::editor::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Editor1",
        from = "seconder2",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub editor_1: HasOne<super::editor::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
