//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "country_area")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub area: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::area::Entity",
        from = "Column::Area",
        to = "super::area::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Area,
    #[sea_orm(has_many = "super::release_country::Entity")]
    ReleaseCountry,
}

impl Related<super::area::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Area.def()
    }
}

impl Related<super::release_country::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseCountry.def()
    }
}

impl Related<super::release::Entity> for Entity {
    fn to() -> RelationDef {
        super::release_country::Relation::Release.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::release_country::Relation::CountryArea.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::area::Entity")]
    Area,
    #[sea_orm(entity = "super::release_country::Entity")]
    ReleaseCountry,
    #[sea_orm(entity = "super::release::Entity")]
    Release,
}
