//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "deleted_entity")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub gid: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub data: Json,
    pub deleted_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::editor_collection_deleted_entity::Entity")]
    EditorCollectionDeletedEntity,
    #[sea_orm(has_many = "super::editor_subscribe_artist_deleted::Entity")]
    EditorSubscribeArtistDeleted,
    #[sea_orm(has_many = "super::editor_subscribe_label_deleted::Entity")]
    EditorSubscribeLabelDeleted,
    #[sea_orm(has_many = "super::editor_subscribe_series_deleted::Entity")]
    EditorSubscribeSeriesDeleted,
}

impl Related<super::editor_collection_deleted_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditorCollectionDeletedEntity.def()
    }
}

impl Related<super::editor_subscribe_artist_deleted::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditorSubscribeArtistDeleted.def()
    }
}

impl Related<super::editor_subscribe_label_deleted::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditorSubscribeLabelDeleted.def()
    }
}

impl Related<super::editor_subscribe_series_deleted::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditorSubscribeSeriesDeleted.def()
    }
}

impl Related<super::editor_collection::Entity> for Entity {
    fn to() -> RelationDef {
        super::editor_collection_deleted_entity::Relation::EditorCollection.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::editor_collection_deleted_entity::Relation::DeletedEntity
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::editor_collection_deleted_entity::Entity")]
    EditorCollectionDeletedEntity,
    #[sea_orm(entity = "super::editor_subscribe_artist_deleted::Entity")]
    EditorSubscribeArtistDeleted,
    #[sea_orm(entity = "super::editor_subscribe_label_deleted::Entity")]
    EditorSubscribeLabelDeleted,
    #[sea_orm(entity = "super::editor_subscribe_series_deleted::Entity")]
    EditorSubscribeSeriesDeleted,
    #[sea_orm(entity = "super::editor_collection::Entity")]
    EditorCollection,
}
