//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "deleted_entity")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub gid: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub data: Json,
    pub deleted_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub editor_subscribe_artist_deleteds: HasMany<super::editor_subscribe_artist_deleted::Entity>,
    #[sea_orm(has_many)]
    pub editor_subscribe_label_deleteds: HasMany<super::editor_subscribe_label_deleted::Entity>,
    #[sea_orm(has_many)]
    pub editor_subscribe_series_deleteds: HasMany<super::editor_subscribe_series_deleted::Entity>,
    #[sea_orm(has_many, via = "editor_collection_deleted_entity")]
    pub editor_collections: HasMany<super::editor_collection::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
