//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "deleted_entity")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub gid: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub data: Json,
    pub deleted_at: DateTimeWithTimeZone,
}


impl ActiveModelBehavior for ActiveModel {}
