//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "editor")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub privs: Option<i32>,
    pub email: Option<String>,
    pub website: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub bio: Option<String>,
    pub member_since: Option<DateTimeWithTimeZone>,
    pub email_confirm_date: Option<DateTimeWithTimeZone>,
    pub last_login_date: Option<DateTimeWithTimeZone>,
    pub last_updated: Option<DateTimeWithTimeZone>,
    pub birth_date: Option<Date>,
    pub gender: Option<i32>,
    pub area: Option<i32>,
    pub password: String,
    pub ha1: String,
    pub deleted: bool,
}


impl ActiveModelBehavior for ActiveModel {}
