//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "edit_mood")]
pub struct Model {
    #[sea_orm(
        belongs_to,
        from = "edit",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction",
        primary_key,
        auto_increment = false
    )]
    pub edit: i32,
    #[sea_orm(
        belongs_to,
        from = "mood",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade",
        primary_key,
        auto_increment = false
    )]
    pub mood: i32,
    #[sea_orm(
        belongs_to,
        from = "edit",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub edit: HasOne<super::edit::Entity>,
    #[sea_orm(
        belongs_to,
        from = "mood",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub mood: HasOne<super::mood::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
