//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use super::sea_orm_active_enums::Fluency;
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "editor_language")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub editor: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub language: i32,
    pub fluency: Fluency,
}


impl ActiveModelBehavior for ActiveModel {}
