//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "edit_instrument")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub edit: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub instrument: i32,
}


#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
