//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "editor_collection_work")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub collection: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub work: i32,
    pub added: Option<DateTimeWithTimeZone>,
    pub position: i32,
    #[sea_orm(column_type = "Text")]
    pub comment: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::editor_collection::Entity",
        from = "Column::Collection",
        to = "super::editor_collection::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    EditorCollection,
    #[sea_orm(
        belongs_to = "super::work::Entity",
        from = "Column::Work",
        to = "super::work::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Work,
}

impl Related<super::editor_collection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditorCollection.def()
    }
}

impl Related<super::work::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Work.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::editor_collection::Entity")]
    EditorCollection,
    #[sea_orm(entity = "super::work::Entity")]
    Work,
}
