//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "editor_subscribe_artist")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub editor: i32,
    pub artist: i32,
    pub last_edit_sent: i32,
}


impl ActiveModelBehavior for ActiveModel {}
