//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "edit_place")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub edit: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub place: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::edit::Entity",
        from = "Column::Edit",
        to = "super::edit::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Edit,
    #[sea_orm(
        belongs_to = "super::place::Entity",
        from = "Column::Place",
        to = "super::place::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Place,
}

impl Related<super::edit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Edit.def()
    }
}

impl Related<super::place::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Place.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::edit::Entity")]
    Edit,
    #[sea_orm(entity = "super::place::Entity")]
    Place,
}
