//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "edit")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub editor: i32,
    pub r#type: i16,
    pub status: i16,
    pub autoedit: i16,
    pub open_time: Option<DateTimeWithTimeZone>,
    pub close_time: Option<DateTimeWithTimeZone>,
    pub expire_time: DateTimeWithTimeZone,
    pub language: Option<i32>,
    pub quality: i16,
}


impl ActiveModelBehavior for ActiveModel {}
