//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use super::sea_orm_active_enums::OauthCodeChallengeMethod;
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "editor_oauth_token")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub editor: i32,
    pub application: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub authorization_code: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub refresh_token: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub access_token: Option<String>,
    pub expire_time: DateTimeWithTimeZone,
    pub scope: i32,
    pub granted: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub code_challenge: Option<String>,
    pub code_challenge_method: Option<OauthCodeChallengeMethod>,
}


impl ActiveModelBehavior for ActiveModel {}
