//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "editor_subscribe_editor")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub editor: i32,
    pub subscribed_editor: i32,
    pub last_edit_sent: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::editor::Entity",
        from = "Column::Editor",
        to = "super::editor::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Editor2,
    #[sea_orm(
        belongs_to = "super::editor::Entity",
        from = "Column::SubscribedEditor",
        to = "super::editor::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Editor1,
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::editor::Entity", def = "Relation::Editor2.def()")]
    Editor2,
    #[sea_orm(entity = "super::editor::Entity", def = "Relation::Editor1.def()")]
    Editor1,
}
