//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(
    schema_name = "musicbrainz",
    table_name = "editor_collection_gid_redirect"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub gid: Uuid,
    pub new_id: i32,
    pub created: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::editor_collection::Entity",
        from = "Column::NewId",
        to = "super::editor_collection::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    EditorCollection,
}

impl Related<super::editor_collection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditorCollection.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::editor_collection::Entity")]
    EditorCollection,
}
