//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(
    schema_name = "musicbrainz",
    table_name = "editor_collection_release_group"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub collection: i32,
    #[sea_orm(
        belongs_to,
        from = "release_group",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction",
        primary_key,
        auto_increment = false
    )]
    pub release_group: i32,
    pub added: Option<DateTimeWithTimeZone>,
    pub position: i32,
    #[sea_orm(column_type = "Text")]
    pub comment: String,
    #[sea_orm(
        belongs_to,
        from = "collection",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub editor_collection: HasOne<super::editor_collection::Entity>,
    #[sea_orm(
        belongs_to,
        from = "release_group",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub release_group: HasOne<super::release_group::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
