//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "editor_subscribe_label")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub editor: i32,
    pub label: i32,
    pub last_edit_sent: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::edit::Entity",
        from = "Column::LastEditSent",
        to = "super::edit::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Edit,
    #[sea_orm(
        belongs_to = "super::editor::Entity",
        from = "Column::Editor",
        to = "super::editor::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Editor,
    #[sea_orm(
        belongs_to = "super::label::Entity",
        from = "Column::Label",
        to = "super::label::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Label,
}

impl Related<super::edit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Edit.def()
    }
}

impl Related<super::editor::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Editor.def()
    }
}

impl Related<super::label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Label.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::edit::Entity")]
    Edit,
    #[sea_orm(entity = "super::editor::Entity")]
    Editor,
    #[sea_orm(entity = "super::label::Entity")]
    Label,
}
