//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "editor_collection_series")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub collection: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub series: i32,
    pub added: Option<DateTimeWithTimeZone>,
    pub position: i32,
    #[sea_orm(column_type = "Text")]
    pub comment: String,
}


#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
