//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "edit")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub editor: i32,
    pub r#type: i16,
    pub status: i16,
    pub autoedit: i16,
    pub open_time: Option<DateTimeWithTimeZone>,
    pub close_time: Option<DateTimeWithTimeZone>,
    pub expire_time: DateTimeWithTimeZone,
    pub language: Option<i32>,
    pub quality: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::edit_area::Entity")]
    EditArea,
    #[sea_orm(has_many = "super::edit_artist::Entity")]
    EditArtist,
    #[sea_orm(has_one = "super::edit_data::Entity")]
    EditData,
    #[sea_orm(has_many = "super::edit_event::Entity")]
    EditEvent,
    #[sea_orm(has_many = "super::edit_genre::Entity")]
    EditGenre,
    #[sea_orm(has_many = "super::edit_instrument::Entity")]
    EditInstrument,
    #[sea_orm(has_many = "super::edit_label::Entity")]
    EditLabel,
    #[sea_orm(has_many = "super::edit_mood::Entity")]
    EditMood,
    #[sea_orm(has_many = "super::edit_note::Entity")]
    EditNote,
    #[sea_orm(has_many = "super::edit_place::Entity")]
    EditPlace,
    #[sea_orm(has_many = "super::edit_recording::Entity")]
    EditRecording,
    #[sea_orm(has_many = "super::edit_release::Entity")]
    EditRelease,
    #[sea_orm(has_many = "super::edit_release_group::Entity")]
    EditReleaseGroup,
    #[sea_orm(has_many = "super::edit_series::Entity")]
    EditSeries,
    #[sea_orm(has_many = "super::edit_url::Entity")]
    EditUrl,
    #[sea_orm(has_many = "super::edit_work::Entity")]
    EditWork,
    #[sea_orm(
        belongs_to = "super::editor::Entity",
        from = "Column::Editor",
        to = "super::editor::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Editor,
    #[sea_orm(has_many = "super::editor_subscribe_artist::Entity")]
    EditorSubscribeArtist,
    #[sea_orm(has_many = "super::editor_subscribe_artist_deleted::Entity")]
    EditorSubscribeArtistDeleted,
    #[sea_orm(has_many = "super::editor_subscribe_label::Entity")]
    EditorSubscribeLabel,
    #[sea_orm(has_many = "super::editor_subscribe_label_deleted::Entity")]
    EditorSubscribeLabelDeleted,
    #[sea_orm(has_many = "super::editor_subscribe_series::Entity")]
    EditorSubscribeSeries,
    #[sea_orm(has_many = "super::editor_subscribe_series_deleted::Entity")]
    EditorSubscribeSeriesDeleted,
    #[sea_orm(
        belongs_to = "super::language::Entity",
        from = "Column::Language",
        to = "super::language::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Language,
    #[sea_orm(has_many = "super::vote::Entity")]
    Vote,
}

impl Related<super::edit_area::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditArea.def()
    }
}

impl Related<super::edit_artist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditArtist.def()
    }
}

impl Related<super::edit_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditData.def()
    }
}

impl Related<super::edit_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditEvent.def()
    }
}

impl Related<super::edit_genre::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditGenre.def()
    }
}

impl Related<super::edit_instrument::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditInstrument.def()
    }
}

impl Related<super::edit_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditLabel.def()
    }
}

impl Related<super::edit_mood::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditMood.def()
    }
}

impl Related<super::edit_note::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditNote.def()
    }
}

impl Related<super::edit_place::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditPlace.def()
    }
}

impl Related<super::edit_recording::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditRecording.def()
    }
}

impl Related<super::edit_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditRelease.def()
    }
}

impl Related<super::edit_release_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditReleaseGroup.def()
    }
}

impl Related<super::edit_series::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditSeries.def()
    }
}

impl Related<super::edit_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditUrl.def()
    }
}

impl Related<super::edit_work::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditWork.def()
    }
}

impl Related<super::editor::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Editor.def()
    }
}

impl Related<super::editor_subscribe_artist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditorSubscribeArtist.def()
    }
}

impl Related<super::editor_subscribe_artist_deleted::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditorSubscribeArtistDeleted.def()
    }
}

impl Related<super::editor_subscribe_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditorSubscribeLabel.def()
    }
}

impl Related<super::editor_subscribe_label_deleted::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditorSubscribeLabelDeleted.def()
    }
}

impl Related<super::editor_subscribe_series::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditorSubscribeSeries.def()
    }
}

impl Related<super::editor_subscribe_series_deleted::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditorSubscribeSeriesDeleted.def()
    }
}

impl Related<super::language::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Language.def()
    }
}

impl Related<super::vote::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Vote.def()
    }
}

impl Related<super::area::Entity> for Entity {
    fn to() -> RelationDef {
        super::edit_area::Relation::Area.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::edit_area::Relation::Edit.def().rev())
    }
}

impl Related<super::artist::Entity> for Entity {
    fn to() -> RelationDef {
        super::edit_artist::Relation::Artist.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::edit_artist::Relation::Edit.def().rev())
    }
}

impl Related<super::event::Entity> for Entity {
    fn to() -> RelationDef {
        super::edit_event::Relation::Event.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::edit_event::Relation::Edit.def().rev())
    }
}

impl Related<super::genre::Entity> for Entity {
    fn to() -> RelationDef {
        super::edit_genre::Relation::Genre.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::edit_genre::Relation::Edit.def().rev())
    }
}

impl Related<super::instrument::Entity> for Entity {
    fn to() -> RelationDef {
        super::edit_instrument::Relation::Instrument.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::edit_instrument::Relation::Edit.def().rev())
    }
}

impl Related<super::label::Entity> for Entity {
    fn to() -> RelationDef {
        super::edit_label::Relation::Label.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::edit_label::Relation::Edit.def().rev())
    }
}

impl Related<super::mood::Entity> for Entity {
    fn to() -> RelationDef {
        super::edit_mood::Relation::Mood.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::edit_mood::Relation::Edit.def().rev())
    }
}

impl Related<super::place::Entity> for Entity {
    fn to() -> RelationDef {
        super::edit_place::Relation::Place.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::edit_place::Relation::Edit.def().rev())
    }
}

impl Related<super::recording::Entity> for Entity {
    fn to() -> RelationDef {
        super::edit_recording::Relation::Recording.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::edit_recording::Relation::Edit.def().rev())
    }
}

impl Related<super::release::Entity> for Entity {
    fn to() -> RelationDef {
        super::edit_release::Relation::Release.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::edit_release::Relation::Edit.def().rev())
    }
}

impl Related<super::release_group::Entity> for Entity {
    fn to() -> RelationDef {
        super::edit_release_group::Relation::ReleaseGroup.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::edit_release_group::Relation::Edit.def().rev())
    }
}

impl Related<super::series::Entity> for Entity {
    fn to() -> RelationDef {
        super::edit_series::Relation::Series.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::edit_series::Relation::Edit.def().rev())
    }
}

impl Related<super::url::Entity> for Entity {
    fn to() -> RelationDef {
        super::edit_url::Relation::Url.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::edit_url::Relation::Edit.def().rev())
    }
}

impl Related<super::work::Entity> for Entity {
    fn to() -> RelationDef {
        super::edit_work::Relation::Work.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::edit_work::Relation::Edit.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::edit_area::Entity")]
    EditArea,
    #[sea_orm(entity = "super::edit_artist::Entity")]
    EditArtist,
    #[sea_orm(entity = "super::edit_data::Entity")]
    EditData,
    #[sea_orm(entity = "super::edit_event::Entity")]
    EditEvent,
    #[sea_orm(entity = "super::edit_genre::Entity")]
    EditGenre,
    #[sea_orm(entity = "super::edit_instrument::Entity")]
    EditInstrument,
    #[sea_orm(entity = "super::edit_label::Entity")]
    EditLabel,
    #[sea_orm(entity = "super::edit_mood::Entity")]
    EditMood,
    #[sea_orm(entity = "super::edit_note::Entity")]
    EditNote,
    #[sea_orm(entity = "super::edit_place::Entity")]
    EditPlace,
    #[sea_orm(entity = "super::edit_recording::Entity")]
    EditRecording,
    #[sea_orm(entity = "super::edit_release::Entity")]
    EditRelease,
    #[sea_orm(entity = "super::edit_release_group::Entity")]
    EditReleaseGroup,
    #[sea_orm(entity = "super::edit_series::Entity")]
    EditSeries,
    #[sea_orm(entity = "super::edit_url::Entity")]
    EditUrl,
    #[sea_orm(entity = "super::edit_work::Entity")]
    EditWork,
    #[sea_orm(entity = "super::editor::Entity")]
    Editor,
    #[sea_orm(entity = "super::editor_subscribe_artist::Entity")]
    EditorSubscribeArtist,
    #[sea_orm(entity = "super::editor_subscribe_artist_deleted::Entity")]
    EditorSubscribeArtistDeleted,
    #[sea_orm(entity = "super::editor_subscribe_label::Entity")]
    EditorSubscribeLabel,
    #[sea_orm(entity = "super::editor_subscribe_label_deleted::Entity")]
    EditorSubscribeLabelDeleted,
    #[sea_orm(entity = "super::editor_subscribe_series::Entity")]
    EditorSubscribeSeries,
    #[sea_orm(entity = "super::editor_subscribe_series_deleted::Entity")]
    EditorSubscribeSeriesDeleted,
    #[sea_orm(entity = "super::language::Entity")]
    Language,
    #[sea_orm(entity = "super::vote::Entity")]
    Vote,
    #[sea_orm(entity = "super::area::Entity")]
    Area,
    #[sea_orm(entity = "super::artist::Entity")]
    Artist,
    #[sea_orm(entity = "super::event::Entity")]
    Event,
    #[sea_orm(entity = "super::genre::Entity")]
    Genre,
    #[sea_orm(entity = "super::instrument::Entity")]
    Instrument,
    #[sea_orm(entity = "super::label::Entity")]
    Label,
    #[sea_orm(entity = "super::mood::Entity")]
    Mood,
    #[sea_orm(entity = "super::place::Entity")]
    Place,
    #[sea_orm(entity = "super::recording::Entity")]
    Recording,
    #[sea_orm(entity = "super::release::Entity")]
    Release,
    #[sea_orm(entity = "super::release_group::Entity")]
    ReleaseGroup,
    #[sea_orm(entity = "super::series::Entity")]
    Series,
    #[sea_orm(entity = "super::url::Entity")]
    Url,
    #[sea_orm(entity = "super::work::Entity")]
    Work,
}
