//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "event")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub gid: Uuid,
    pub name: String,
    pub begin_date_year: Option<i16>,
    pub begin_date_month: Option<i16>,
    pub begin_date_day: Option<i16>,
    pub end_date_year: Option<i16>,
    pub end_date_month: Option<i16>,
    pub end_date_day: Option<i16>,
    pub time: Option<Time>,
    pub r#type: Option<i32>,
    pub cancelled: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub setlist: Option<String>,
    pub comment: String,
    pub edits_pending: i32,
    pub last_updated: Option<DateTimeWithTimeZone>,
    pub ended: bool,
}


impl ActiveModelBehavior for ActiveModel {}
