//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "event")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub gid: Uuid,
    pub name: String,
    pub begin_date_year: Option<i16>,
    pub begin_date_month: Option<i16>,
    pub begin_date_day: Option<i16>,
    pub end_date_year: Option<i16>,
    pub end_date_month: Option<i16>,
    pub end_date_day: Option<i16>,
    pub time: Option<Time>,
    pub r#type: Option<i32>,
    pub cancelled: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub setlist: Option<String>,
    pub comment: String,
    pub edits_pending: i32,
    pub last_updated: Option<DateTimeWithTimeZone>,
    pub ended: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::edit_event::Entity")]
    EditEvent,
    #[sea_orm(has_many = "super::editor_collection_event::Entity")]
    EditorCollectionEvent,
    #[sea_orm(has_many = "super::event_alias::Entity")]
    EventAlias,
    #[sea_orm(has_many = "super::event_annotation::Entity")]
    EventAnnotation,
    #[sea_orm(has_many = "super::event_attribute::Entity")]
    EventAttribute,
    #[sea_orm(has_many = "super::event_gid_redirect::Entity")]
    EventGidRedirect,
    #[sea_orm(has_one = "super::event_meta::Entity")]
    EventMeta,
    #[sea_orm(has_many = "super::event_rating_raw::Entity")]
    EventRatingRaw,
    #[sea_orm(has_many = "super::event_tag::Entity")]
    EventTag,
    #[sea_orm(has_many = "super::event_tag_raw::Entity")]
    EventTagRaw,
    #[sea_orm(
        belongs_to = "super::event_type::Entity",
        from = "Column::Type",
        to = "super::event_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    EventType,
    #[sea_orm(has_many = "super::l_area_event::Entity")]
    LAreaEvent,
    #[sea_orm(has_many = "super::l_artist_event::Entity")]
    LArtistEvent,
    #[sea_orm(has_many = "super::l_event_genre::Entity")]
    LEventGenre,
    #[sea_orm(has_many = "super::l_event_instrument::Entity")]
    LEventInstrument,
    #[sea_orm(has_many = "super::l_event_label::Entity")]
    LEventLabel,
    #[sea_orm(has_many = "super::l_event_mood::Entity")]
    LEventMood,
    #[sea_orm(has_many = "super::l_event_place::Entity")]
    LEventPlace,
    #[sea_orm(has_many = "super::l_event_recording::Entity")]
    LEventRecording,
    #[sea_orm(has_many = "super::l_event_release::Entity")]
    LEventRelease,
    #[sea_orm(has_many = "super::l_event_release_group::Entity")]
    LEventReleaseGroup,
    #[sea_orm(has_many = "super::l_event_series::Entity")]
    LEventSeries,
    #[sea_orm(has_many = "super::l_event_url::Entity")]
    LEventUrl,
    #[sea_orm(has_many = "super::l_event_work::Entity")]
    LEventWork,
}

impl Related<super::edit_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditEvent.def()
    }
}

impl Related<super::editor_collection_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditorCollectionEvent.def()
    }
}

impl Related<super::event_alias::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventAlias.def()
    }
}

impl Related<super::event_annotation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventAnnotation.def()
    }
}

impl Related<super::event_attribute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventAttribute.def()
    }
}

impl Related<super::event_gid_redirect::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventGidRedirect.def()
    }
}

impl Related<super::event_meta::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventMeta.def()
    }
}

impl Related<super::event_rating_raw::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventRatingRaw.def()
    }
}

impl Related<super::event_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventTag.def()
    }
}

impl Related<super::event_tag_raw::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventTagRaw.def()
    }
}

impl Related<super::event_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventType.def()
    }
}

impl Related<super::l_area_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaEvent.def()
    }
}

impl Related<super::l_artist_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistEvent.def()
    }
}

impl Related<super::l_event_genre::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LEventGenre.def()
    }
}

impl Related<super::l_event_instrument::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LEventInstrument.def()
    }
}

impl Related<super::l_event_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LEventLabel.def()
    }
}

impl Related<super::l_event_mood::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LEventMood.def()
    }
}

impl Related<super::l_event_place::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LEventPlace.def()
    }
}

impl Related<super::l_event_recording::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LEventRecording.def()
    }
}

impl Related<super::l_event_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LEventRelease.def()
    }
}

impl Related<super::l_event_release_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LEventReleaseGroup.def()
    }
}

impl Related<super::l_event_series::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LEventSeries.def()
    }
}

impl Related<super::l_event_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LEventUrl.def()
    }
}

impl Related<super::l_event_work::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LEventWork.def()
    }
}

impl Related<super::annotation::Entity> for Entity {
    fn to() -> RelationDef {
        super::event_annotation::Relation::Annotation.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::event_annotation::Relation::Event.def().rev())
    }
}

impl Related<super::edit::Entity> for Entity {
    fn to() -> RelationDef {
        super::edit_event::Relation::Edit.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::edit_event::Relation::Event.def().rev())
    }
}

impl Related<super::editor::Entity> for Entity {
    fn to() -> RelationDef {
        super::event_rating_raw::Relation::Editor.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::event_rating_raw::Relation::Event.def().rev())
    }
}

impl Related<super::editor_collection::Entity> for Entity {
    fn to() -> RelationDef {
        super::editor_collection_event::Relation::EditorCollection.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::editor_collection_event::Relation::Event.def().rev())
    }
}

impl Related<super::tag::Entity> for Entity {
    fn to() -> RelationDef {
        super::event_tag::Relation::Tag.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::event_tag::Relation::Event.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::edit_event::Entity")]
    EditEvent,
    #[sea_orm(entity = "super::editor_collection_event::Entity")]
    EditorCollectionEvent,
    #[sea_orm(entity = "super::event_alias::Entity")]
    EventAlias,
    #[sea_orm(entity = "super::event_annotation::Entity")]
    EventAnnotation,
    #[sea_orm(entity = "super::event_attribute::Entity")]
    EventAttribute,
    #[sea_orm(entity = "super::event_gid_redirect::Entity")]
    EventGidRedirect,
    #[sea_orm(entity = "super::event_meta::Entity")]
    EventMeta,
    #[sea_orm(entity = "super::event_rating_raw::Entity")]
    EventRatingRaw,
    #[sea_orm(entity = "super::event_tag::Entity")]
    EventTag,
    #[sea_orm(entity = "super::event_tag_raw::Entity")]
    EventTagRaw,
    #[sea_orm(entity = "super::event_type::Entity")]
    EventType,
    #[sea_orm(entity = "super::l_area_event::Entity")]
    LAreaEvent,
    #[sea_orm(entity = "super::l_artist_event::Entity")]
    LArtistEvent,
    #[sea_orm(entity = "super::l_event_genre::Entity")]
    LEventGenre,
    #[sea_orm(entity = "super::l_event_instrument::Entity")]
    LEventInstrument,
    #[sea_orm(entity = "super::l_event_label::Entity")]
    LEventLabel,
    #[sea_orm(entity = "super::l_event_mood::Entity")]
    LEventMood,
    #[sea_orm(entity = "super::l_event_place::Entity")]
    LEventPlace,
    #[sea_orm(entity = "super::l_event_recording::Entity")]
    LEventRecording,
    #[sea_orm(entity = "super::l_event_release::Entity")]
    LEventRelease,
    #[sea_orm(entity = "super::l_event_release_group::Entity")]
    LEventReleaseGroup,
    #[sea_orm(entity = "super::l_event_series::Entity")]
    LEventSeries,
    #[sea_orm(entity = "super::l_event_url::Entity")]
    LEventUrl,
    #[sea_orm(entity = "super::l_event_work::Entity")]
    LEventWork,
    #[sea_orm(entity = "super::annotation::Entity")]
    Annotation,
    #[sea_orm(entity = "super::edit::Entity")]
    Edit,
    #[sea_orm(entity = "super::editor::Entity")]
    Editor,
    #[sea_orm(entity = "super::editor_collection::Entity")]
    EditorCollection,
    #[sea_orm(entity = "super::tag::Entity")]
    Tag,
}
