//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "event_tag_raw")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub event: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub editor: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub tag: i32,
    pub is_upvote: bool,
}


impl ActiveModelBehavior for ActiveModel {}
