//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "genre")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub gid: Uuid,
    pub name: String,
    pub comment: String,
    pub edits_pending: i32,
    pub last_updated: Option<DateTimeWithTimeZone>,
    #[sea_orm(has_many)]
    pub genre_aliases: HasMany<super::genre_alias::Entity>,
    #[sea_orm(has_many)]
    pub l_area_genres: HasMany<super::l_area_genre::Entity>,
    #[sea_orm(has_many)]
    pub l_artist_genres: HasMany<super::l_artist_genre::Entity>,
    #[sea_orm(has_many)]
    pub l_event_genres: HasMany<super::l_event_genre::Entity>,
    #[sea_orm(has_many)]
    pub l_genre_instruments: HasMany<super::l_genre_instrument::Entity>,
    #[sea_orm(has_many)]
    pub l_genre_labels: HasMany<super::l_genre_label::Entity>,
    #[sea_orm(has_many)]
    pub l_genre_moods: HasMany<super::l_genre_mood::Entity>,
    #[sea_orm(has_many)]
    pub l_genre_places: HasMany<super::l_genre_place::Entity>,
    #[sea_orm(has_many)]
    pub l_genre_recordings: HasMany<super::l_genre_recording::Entity>,
    #[sea_orm(has_many)]
    pub l_genre_releases: HasMany<super::l_genre_release::Entity>,
    #[sea_orm(has_many)]
    pub l_genre_release_groups: HasMany<super::l_genre_release_group::Entity>,
    #[sea_orm(has_many)]
    pub l_genre_series: HasMany<super::l_genre_series::Entity>,
    #[sea_orm(has_many)]
    pub l_genre_urls: HasMany<super::l_genre_url::Entity>,
    #[sea_orm(has_many)]
    pub l_genre_works: HasMany<super::l_genre_work::Entity>,
    #[sea_orm(has_many, via = "genre_annotation")]
    pub annotations: HasMany<super::annotation::Entity>,
    #[sea_orm(has_many, via = "edit_genre")]
    pub edits: HasMany<super::edit::Entity>,
    #[sea_orm(has_many, via = "editor_collection_genre")]
    pub editor_collections: HasMany<super::editor_collection::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
