//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "genre_alias")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub genre: i32,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub locale: Option<String>,
    pub edits_pending: i32,
    pub last_updated: Option<DateTimeWithTimeZone>,
    pub r#type: Option<i32>,
    pub sort_name: String,
    pub begin_date_year: Option<i16>,
    pub begin_date_month: Option<i16>,
    pub begin_date_day: Option<i16>,
    pub end_date_year: Option<i16>,
    pub end_date_month: Option<i16>,
    pub end_date_day: Option<i16>,
    pub primary_for_locale: bool,
    pub ended: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::genre::Entity",
        from = "Column::Genre",
        to = "super::genre::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Genre,
    #[sea_orm(
        belongs_to = "super::genre_alias_type::Entity",
        from = "Column::Type",
        to = "super::genre_alias_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    GenreAliasType,
}

impl Related<super::genre::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Genre.def()
    }
}

impl Related<super::genre_alias_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GenreAliasType.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::genre::Entity")]
    Genre,
    #[sea_orm(entity = "super::genre_alias_type::Entity")]
    GenreAliasType,
}
