//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "iso_3166_1")]
pub struct Model {
    pub area: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub code: String,
}


impl ActiveModelBehavior for ActiveModel {}
