//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "isrc")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub recording: i32,
    pub isrc: String,
    pub source: Option<i16>,
    pub edits_pending: i32,
    pub created: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::recording::Entity",
        from = "Column::Recording",
        to = "super::recording::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Recording,
}

impl Related<super::recording::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Recording.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::recording::Entity")]
    Recording,
}
