//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "isrc")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub recording: i32,
    #[sea_orm(unique_key = "isrc_idx_isrc_recording")]
    pub isrc: String,
    pub source: Option<i16>,
    pub edits_pending: i32,
    pub created: Option<DateTimeWithTimeZone>,
}


impl ActiveModelBehavior for ActiveModel {}
