//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "iswc")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub work: i32,
    pub iswc: Option<String>,
    pub source: Option<i16>,
    pub edits_pending: i32,
    pub created: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::work::Entity",
        from = "Column::Work",
        to = "super::work::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Work,
}

impl Related<super::work::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Work.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::work::Entity")]
    Work,
}
