//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "iswc")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub work: i32,
    #[sea_orm(unique_key = "iswc_idx_iswc")]
    pub iswc: Option<String>,
    pub source: Option<i16>,
    pub edits_pending: i32,
    pub created: DateTimeWithTimeZone,
}


impl ActiveModelBehavior for ActiveModel {}
