//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "l_artist_artist")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub link: i32,
    pub entity0: i32,
    pub entity1: i32,
    pub edits_pending: i32,
    pub last_updated: Option<DateTimeWithTimeZone>,
    pub link_order: i32,
    #[sea_orm(column_type = "Text")]
    pub entity0_credit: String,
    #[sea_orm(column_type = "Text")]
    pub entity1_credit: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::artist::Entity",
        from = "Column::Entity0",
        to = "super::artist::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Artist2,
    #[sea_orm(
        belongs_to = "super::artist::Entity",
        from = "Column::Entity1",
        to = "super::artist::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Artist1,
    #[sea_orm(
        belongs_to = "super::link::Entity",
        from = "Column::Link",
        to = "super::link::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Link,
}

impl Related<super::link::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Link.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::artist::Entity", def = "Relation::Artist2.def()")]
    Artist2,
    #[sea_orm(entity = "super::artist::Entity", def = "Relation::Artist1.def()")]
    Artist1,
    #[sea_orm(entity = "super::link::Entity")]
    Link,
}
