//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "l_genre_instrument")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub link: i32,
    #[sea_orm(unique_key = "l_genre_instrument_idx_uniq")]
    pub entity0: i32,
    #[sea_orm(unique_key = "l_genre_instrument_idx_uniq")]
    pub entity1: i32,
    pub edits_pending: i32,
    pub last_updated: Option<DateTimeWithTimeZone>,
    #[sea_orm(unique_key = "l_genre_instrument_idx_uniq")]
    pub link_order: i32,
    #[sea_orm(column_type = "Text")]
    pub entity0_credit: String,
    #[sea_orm(column_type = "Text")]
    pub entity1_credit: String,
}


impl ActiveModelBehavior for ActiveModel {}
