//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "label_meta")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub rating: Option<i16>,
    pub rating_count: Option<i32>,
    #[sea_orm(
        belongs_to,
        from = "id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub label: HasOne<super::label::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
