//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "label_attribute")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub label: i32,
    pub label_attribute_type: i32,
    pub label_attribute_type_allowed_value: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub label_attribute_text: Option<String>,
}


impl ActiveModelBehavior for ActiveModel {}
