//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "label_attribute")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub label: i32,
    pub label_attribute_type: i32,
    pub label_attribute_type_allowed_value: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub label_attribute_text: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::label::Entity",
        from = "Column::Label",
        to = "super::label::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Label,
    #[sea_orm(
        belongs_to = "super::label_attribute_type::Entity",
        from = "Column::LabelAttributeType",
        to = "super::label_attribute_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    LabelAttributeType,
    #[sea_orm(
        belongs_to = "super::label_attribute_type_allowed_value::Entity",
        from = "Column::LabelAttributeTypeAllowedValue",
        to = "super::label_attribute_type_allowed_value::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    LabelAttributeTypeAllowedValue,
}

impl Related<super::label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Label.def()
    }
}

impl Related<super::label_attribute_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LabelAttributeType.def()
    }
}

impl Related<super::label_attribute_type_allowed_value::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LabelAttributeTypeAllowedValue.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::label::Entity")]
    Label,
    #[sea_orm(entity = "super::label_attribute_type::Entity")]
    LabelAttributeType,
    #[sea_orm(entity = "super::label_attribute_type_allowed_value::Entity")]
    LabelAttributeTypeAllowedValue,
}
