//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "label")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub gid: Uuid,
    #[sea_orm(unique)]
    pub name: String,
    pub begin_date_year: Option<i16>,
    pub begin_date_month: Option<i16>,
    pub begin_date_day: Option<i16>,
    pub end_date_year: Option<i16>,
    pub end_date_month: Option<i16>,
    pub end_date_day: Option<i16>,
    pub label_code: Option<i32>,
    pub r#type: Option<i32>,
    pub area: Option<i32>,
    pub comment: String,
    pub edits_pending: i32,
    pub last_updated: Option<DateTimeWithTimeZone>,
    pub ended: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::area::Entity",
        from = "Column::Area",
        to = "super::area::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Area,
    #[sea_orm(has_many = "super::edit_label::Entity")]
    EditLabel,
    #[sea_orm(has_many = "super::editor_collection_label::Entity")]
    EditorCollectionLabel,
    #[sea_orm(has_many = "super::editor_subscribe_label::Entity")]
    EditorSubscribeLabel,
    #[sea_orm(has_many = "super::l_area_label::Entity")]
    LAreaLabel,
    #[sea_orm(has_many = "super::l_artist_label::Entity")]
    LArtistLabel,
    #[sea_orm(has_many = "super::l_event_label::Entity")]
    LEventLabel,
    #[sea_orm(has_many = "super::l_genre_label::Entity")]
    LGenreLabel,
    #[sea_orm(has_many = "super::l_instrument_label::Entity")]
    LInstrumentLabel,
    #[sea_orm(has_many = "super::l_label_mood::Entity")]
    LLabelMood,
    #[sea_orm(has_many = "super::l_label_place::Entity")]
    LLabelPlace,
    #[sea_orm(has_many = "super::l_label_recording::Entity")]
    LLabelRecording,
    #[sea_orm(has_many = "super::l_label_release::Entity")]
    LLabelRelease,
    #[sea_orm(has_many = "super::l_label_release_group::Entity")]
    LLabelReleaseGroup,
    #[sea_orm(has_many = "super::l_label_series::Entity")]
    LLabelSeries,
    #[sea_orm(has_many = "super::l_label_url::Entity")]
    LLabelUrl,
    #[sea_orm(has_many = "super::l_label_work::Entity")]
    LLabelWork,
    #[sea_orm(has_many = "super::label_alias::Entity")]
    LabelAlias,
    #[sea_orm(has_many = "super::label_annotation::Entity")]
    LabelAnnotation,
    #[sea_orm(has_many = "super::label_attribute::Entity")]
    LabelAttribute,
    #[sea_orm(has_many = "super::label_gid_redirect::Entity")]
    LabelGidRedirect,
    #[sea_orm(has_many = "super::label_ipi::Entity")]
    LabelIpi,
    #[sea_orm(has_many = "super::label_isni::Entity")]
    LabelIsni,
    #[sea_orm(has_one = "super::label_meta::Entity")]
    LabelMeta,
    #[sea_orm(has_many = "super::label_rating_raw::Entity")]
    LabelRatingRaw,
    #[sea_orm(has_many = "super::label_tag::Entity")]
    LabelTag,
    #[sea_orm(has_many = "super::label_tag_raw::Entity")]
    LabelTagRaw,
    #[sea_orm(
        belongs_to = "super::label_type::Entity",
        from = "Column::Type",
        to = "super::label_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    LabelType,
    #[sea_orm(has_many = "super::release_label::Entity")]
    ReleaseLabel,
}

impl Related<super::area::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Area.def()
    }
}

impl Related<super::edit_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditLabel.def()
    }
}

impl Related<super::editor_collection_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditorCollectionLabel.def()
    }
}

impl Related<super::editor_subscribe_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditorSubscribeLabel.def()
    }
}

impl Related<super::l_area_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaLabel.def()
    }
}

impl Related<super::l_artist_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistLabel.def()
    }
}

impl Related<super::l_event_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LEventLabel.def()
    }
}

impl Related<super::l_genre_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LGenreLabel.def()
    }
}

impl Related<super::l_instrument_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LInstrumentLabel.def()
    }
}

impl Related<super::l_label_mood::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LLabelMood.def()
    }
}

impl Related<super::l_label_place::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LLabelPlace.def()
    }
}

impl Related<super::l_label_recording::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LLabelRecording.def()
    }
}

impl Related<super::l_label_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LLabelRelease.def()
    }
}

impl Related<super::l_label_release_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LLabelReleaseGroup.def()
    }
}

impl Related<super::l_label_series::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LLabelSeries.def()
    }
}

impl Related<super::l_label_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LLabelUrl.def()
    }
}

impl Related<super::l_label_work::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LLabelWork.def()
    }
}

impl Related<super::label_alias::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LabelAlias.def()
    }
}

impl Related<super::label_annotation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LabelAnnotation.def()
    }
}

impl Related<super::label_attribute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LabelAttribute.def()
    }
}

impl Related<super::label_gid_redirect::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LabelGidRedirect.def()
    }
}

impl Related<super::label_ipi::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LabelIpi.def()
    }
}

impl Related<super::label_isni::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LabelIsni.def()
    }
}

impl Related<super::label_meta::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LabelMeta.def()
    }
}

impl Related<super::label_rating_raw::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LabelRatingRaw.def()
    }
}

impl Related<super::label_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LabelTag.def()
    }
}

impl Related<super::label_tag_raw::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LabelTagRaw.def()
    }
}

impl Related<super::label_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LabelType.def()
    }
}

impl Related<super::release_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseLabel.def()
    }
}

impl Related<super::annotation::Entity> for Entity {
    fn to() -> RelationDef {
        super::label_annotation::Relation::Annotation.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::label_annotation::Relation::Label.def().rev())
    }
}

impl Related<super::edit::Entity> for Entity {
    fn to() -> RelationDef {
        super::edit_label::Relation::Edit.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::edit_label::Relation::Label.def().rev())
    }
}

impl Related<super::editor::Entity> for Entity {
    fn to() -> RelationDef {
        super::label_rating_raw::Relation::Editor.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::label_rating_raw::Relation::Label.def().rev())
    }
}

impl Related<super::editor_collection::Entity> for Entity {
    fn to() -> RelationDef {
        super::editor_collection_label::Relation::EditorCollection.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::editor_collection_label::Relation::Label.def().rev())
    }
}

impl Related<super::tag::Entity> for Entity {
    fn to() -> RelationDef {
        super::label_tag::Relation::Tag.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::label_tag::Relation::Label.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::area::Entity")]
    Area,
    #[sea_orm(entity = "super::edit_label::Entity")]
    EditLabel,
    #[sea_orm(entity = "super::editor_collection_label::Entity")]
    EditorCollectionLabel,
    #[sea_orm(entity = "super::editor_subscribe_label::Entity")]
    EditorSubscribeLabel,
    #[sea_orm(entity = "super::l_area_label::Entity")]
    LAreaLabel,
    #[sea_orm(entity = "super::l_artist_label::Entity")]
    LArtistLabel,
    #[sea_orm(entity = "super::l_event_label::Entity")]
    LEventLabel,
    #[sea_orm(entity = "super::l_genre_label::Entity")]
    LGenreLabel,
    #[sea_orm(entity = "super::l_instrument_label::Entity")]
    LInstrumentLabel,
    #[sea_orm(entity = "super::l_label_mood::Entity")]
    LLabelMood,
    #[sea_orm(entity = "super::l_label_place::Entity")]
    LLabelPlace,
    #[sea_orm(entity = "super::l_label_recording::Entity")]
    LLabelRecording,
    #[sea_orm(entity = "super::l_label_release::Entity")]
    LLabelRelease,
    #[sea_orm(entity = "super::l_label_release_group::Entity")]
    LLabelReleaseGroup,
    #[sea_orm(entity = "super::l_label_series::Entity")]
    LLabelSeries,
    #[sea_orm(entity = "super::l_label_url::Entity")]
    LLabelUrl,
    #[sea_orm(entity = "super::l_label_work::Entity")]
    LLabelWork,
    #[sea_orm(entity = "super::label_alias::Entity")]
    LabelAlias,
    #[sea_orm(entity = "super::label_annotation::Entity")]
    LabelAnnotation,
    #[sea_orm(entity = "super::label_attribute::Entity")]
    LabelAttribute,
    #[sea_orm(entity = "super::label_gid_redirect::Entity")]
    LabelGidRedirect,
    #[sea_orm(entity = "super::label_ipi::Entity")]
    LabelIpi,
    #[sea_orm(entity = "super::label_isni::Entity")]
    LabelIsni,
    #[sea_orm(entity = "super::label_meta::Entity")]
    LabelMeta,
    #[sea_orm(entity = "super::label_rating_raw::Entity")]
    LabelRatingRaw,
    #[sea_orm(entity = "super::label_tag::Entity")]
    LabelTag,
    #[sea_orm(entity = "super::label_tag_raw::Entity")]
    LabelTagRaw,
    #[sea_orm(entity = "super::label_type::Entity")]
    LabelType,
    #[sea_orm(entity = "super::release_label::Entity")]
    ReleaseLabel,
    #[sea_orm(entity = "super::annotation::Entity")]
    Annotation,
    #[sea_orm(entity = "super::edit::Entity")]
    Edit,
    #[sea_orm(entity = "super::editor::Entity")]
    Editor,
    #[sea_orm(entity = "super::editor_collection::Entity")]
    EditorCollection,
    #[sea_orm(entity = "super::tag::Entity")]
    Tag,
}
