//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "language")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub iso_code_2t: Option<String>,
    #[sea_orm(unique)]
    pub iso_code_2b: Option<String>,
    #[sea_orm(unique)]
    pub iso_code_1: Option<String>,
    pub name: String,
    pub frequency: i16,
    #[sea_orm(unique)]
    pub iso_code_3: Option<String>,
}


#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
