//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "language")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub iso_code_2t: Option<String>,
    #[sea_orm(unique)]
    pub iso_code_2b: Option<String>,
    #[sea_orm(unique)]
    pub iso_code_1: Option<String>,
    pub name: String,
    pub frequency: i16,
    #[sea_orm(unique)]
    pub iso_code_3: Option<String>,
    #[sea_orm(has_many)]
    pub alternative_releases: HasMany<super::alternative_release::Entity>,
    #[sea_orm(has_many)]
    pub edits: HasMany<super::edit::Entity>,
    #[sea_orm(has_many)]
    pub releases: HasMany<super::release::Entity>,
    #[sea_orm(has_many, via = "editor_language")]
    pub editors: HasMany<super::editor::Entity>,
    #[sea_orm(has_many, via = "work_language")]
    pub works: HasMany<super::work::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
