//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

pub mod prelude;

pub mod alternative_medium;
pub mod alternative_medium_track;
pub mod alternative_release;
pub mod alternative_release_type;
pub mod alternative_track;
pub mod annotation;
pub mod application;
pub mod area;
pub mod area_alias;
pub mod area_alias_type;
pub mod area_annotation;
pub mod area_attribute;
pub mod area_attribute_type;
pub mod area_attribute_type_allowed_value;
pub mod area_gid_redirect;
pub mod area_tag;
pub mod area_tag_raw;
pub mod area_type;
pub mod artist;
pub mod artist_alias;
pub mod artist_alias_type;
pub mod artist_annotation;
pub mod artist_attribute;
pub mod artist_attribute_type;
pub mod artist_attribute_type_allowed_value;
pub mod artist_credit;
pub mod artist_credit_gid_redirect;
pub mod artist_credit_name;
pub mod artist_gid_redirect;
pub mod artist_ipi;
pub mod artist_isni;
pub mod artist_meta;
pub mod artist_rating_raw;
pub mod artist_release_group_pending_update;
pub mod artist_release_pending_update;
pub mod artist_tag;
pub mod artist_tag_raw;
pub mod artist_type;
pub mod autoeditor_election;
pub mod autoeditor_election_vote;
pub mod cdtoc;
pub mod cdtoc_raw;
pub mod country_area;
pub mod deleted_entity;
pub mod edit;
pub mod edit_area;
pub mod edit_artist;
pub mod edit_data;
pub mod edit_event;
pub mod edit_genre;
pub mod edit_instrument;
pub mod edit_label;
pub mod edit_mood;
pub mod edit_note;
pub mod edit_note_change;
pub mod edit_note_recipient;
pub mod edit_place;
pub mod edit_recording;
pub mod edit_release;
pub mod edit_release_group;
pub mod edit_series;
pub mod edit_url;
pub mod edit_work;
pub mod editor;
pub mod editor_collection;
pub mod editor_collection_area;
pub mod editor_collection_artist;
pub mod editor_collection_collaborator;
pub mod editor_collection_deleted_entity;
pub mod editor_collection_event;
pub mod editor_collection_genre;
pub mod editor_collection_gid_redirect;
pub mod editor_collection_instrument;
pub mod editor_collection_label;
pub mod editor_collection_place;
pub mod editor_collection_recording;
pub mod editor_collection_release;
pub mod editor_collection_release_group;
pub mod editor_collection_series;
pub mod editor_collection_type;
pub mod editor_collection_work;
pub mod editor_language;
pub mod editor_oauth_token;
pub mod editor_preference;
pub mod editor_subscribe_artist;
pub mod editor_subscribe_artist_deleted;
pub mod editor_subscribe_collection;
pub mod editor_subscribe_editor;
pub mod editor_subscribe_label;
pub mod editor_subscribe_label_deleted;
pub mod editor_subscribe_series;
pub mod editor_subscribe_series_deleted;
pub mod event;
pub mod event_alias;
pub mod event_alias_type;
pub mod event_annotation;
pub mod event_attribute;
pub mod event_attribute_type;
pub mod event_attribute_type_allowed_value;
pub mod event_gid_redirect;
pub mod event_meta;
pub mod event_rating_raw;
pub mod event_tag;
pub mod event_tag_raw;
pub mod event_type;
pub mod gender;
pub mod genre;
pub mod genre_alias;
pub mod genre_alias_type;
pub mod genre_annotation;
pub mod instrument;
pub mod instrument_alias;
pub mod instrument_alias_type;
pub mod instrument_annotation;
pub mod instrument_attribute;
pub mod instrument_attribute_type;
pub mod instrument_attribute_type_allowed_value;
pub mod instrument_gid_redirect;
pub mod instrument_tag;
pub mod instrument_tag_raw;
pub mod instrument_type;
pub mod iso_3166_1;
pub mod iso_3166_2;
pub mod iso_3166_3;
pub mod isrc;
pub mod iswc;
pub mod l_area_area;
pub mod l_area_artist;
pub mod l_area_event;
pub mod l_area_genre;
pub mod l_area_instrument;
pub mod l_area_label;
pub mod l_area_mood;
pub mod l_area_place;
pub mod l_area_recording;
pub mod l_area_release;
pub mod l_area_release_group;
pub mod l_area_series;
pub mod l_area_url;
pub mod l_area_work;
pub mod l_artist_artist;
pub mod l_artist_event;
pub mod l_artist_genre;
pub mod l_artist_instrument;
pub mod l_artist_label;
pub mod l_artist_mood;
pub mod l_artist_place;
pub mod l_artist_recording;
pub mod l_artist_release;
pub mod l_artist_release_group;
pub mod l_artist_series;
pub mod l_artist_url;
pub mod l_artist_work;
pub mod l_event_event;
pub mod l_event_genre;
pub mod l_event_instrument;
pub mod l_event_label;
pub mod l_event_mood;
pub mod l_event_place;
pub mod l_event_recording;
pub mod l_event_release;
pub mod l_event_release_group;
pub mod l_event_series;
pub mod l_event_url;
pub mod l_event_work;
pub mod l_genre_genre;
pub mod l_genre_instrument;
pub mod l_genre_label;
pub mod l_genre_mood;
pub mod l_genre_place;
pub mod l_genre_recording;
pub mod l_genre_release;
pub mod l_genre_release_group;
pub mod l_genre_series;
pub mod l_genre_url;
pub mod l_genre_work;
pub mod l_instrument_instrument;
pub mod l_instrument_label;
pub mod l_instrument_mood;
pub mod l_instrument_place;
pub mod l_instrument_recording;
pub mod l_instrument_release;
pub mod l_instrument_release_group;
pub mod l_instrument_series;
pub mod l_instrument_url;
pub mod l_instrument_work;
pub mod l_label_label;
pub mod l_label_mood;
pub mod l_label_place;
pub mod l_label_recording;
pub mod l_label_release;
pub mod l_label_release_group;
pub mod l_label_series;
pub mod l_label_url;
pub mod l_label_work;
pub mod l_mood_mood;
pub mod l_mood_place;
pub mod l_mood_recording;
pub mod l_mood_release;
pub mod l_mood_release_group;
pub mod l_mood_series;
pub mod l_mood_url;
pub mod l_mood_work;
pub mod l_place_place;
pub mod l_place_recording;
pub mod l_place_release;
pub mod l_place_release_group;
pub mod l_place_series;
pub mod l_place_url;
pub mod l_place_work;
pub mod l_recording_recording;
pub mod l_recording_release;
pub mod l_recording_release_group;
pub mod l_recording_series;
pub mod l_recording_url;
pub mod l_recording_work;
pub mod l_release_group_release_group;
pub mod l_release_group_series;
pub mod l_release_group_url;
pub mod l_release_group_work;
pub mod l_release_release;
pub mod l_release_release_group;
pub mod l_release_series;
pub mod l_release_url;
pub mod l_release_work;
pub mod l_series_series;
pub mod l_series_url;
pub mod l_series_work;
pub mod l_url_url;
pub mod l_url_work;
pub mod l_work_work;
pub mod label;
pub mod label_alias;
pub mod label_alias_type;
pub mod label_annotation;
pub mod label_attribute;
pub mod label_attribute_type;
pub mod label_attribute_type_allowed_value;
pub mod label_gid_redirect;
pub mod label_ipi;
pub mod label_isni;
pub mod label_meta;
pub mod label_rating_raw;
pub mod label_tag;
pub mod label_tag_raw;
pub mod label_type;
pub mod language;
pub mod link;
pub mod link_attribute;
pub mod link_attribute_credit;
pub mod link_attribute_text_value;
pub mod link_attribute_type;
pub mod link_creditable_attribute_type;
pub mod link_text_attribute_type;
pub mod link_type;
pub mod link_type_attribute_type;
pub mod medium;
pub mod medium_attribute;
pub mod medium_attribute_type;
pub mod medium_attribute_type_allowed_format;
pub mod medium_attribute_type_allowed_value;
pub mod medium_attribute_type_allowed_value_allowed_format;
pub mod medium_cdtoc;
pub mod medium_format;
pub mod medium_gid_redirect;
pub mod mood;
pub mod mood_alias;
pub mod mood_alias_type;
pub mod mood_annotation;
pub mod old_editor_name;
pub mod orderable_link_type;
pub mod place;
pub mod place_alias;
pub mod place_alias_type;
pub mod place_annotation;
pub mod place_attribute;
pub mod place_attribute_type;
pub mod place_attribute_type_allowed_value;
pub mod place_gid_redirect;
pub mod place_meta;
pub mod place_rating_raw;
pub mod place_tag;
pub mod place_tag_raw;
pub mod place_type;
pub mod recording;
pub mod recording_alias;
pub mod recording_alias_type;
pub mod recording_annotation;
pub mod recording_attribute;
pub mod recording_attribute_type;
pub mod recording_attribute_type_allowed_value;
pub mod recording_gid_redirect;
pub mod recording_meta;
pub mod recording_rating_raw;
pub mod recording_tag;
pub mod recording_tag_raw;
pub mod release;
pub mod release_alias;
pub mod release_alias_type;
pub mod release_annotation;
pub mod release_attribute;
pub mod release_attribute_type;
pub mod release_attribute_type_allowed_value;
pub mod release_country;
pub mod release_gid_redirect;
pub mod release_group;
pub mod release_group_alias;
pub mod release_group_alias_type;
pub mod release_group_annotation;
pub mod release_group_attribute;
pub mod release_group_attribute_type;
pub mod release_group_attribute_type_allowed_value;
pub mod release_group_gid_redirect;
pub mod release_group_meta;
pub mod release_group_primary_type;
pub mod release_group_rating_raw;
pub mod release_group_secondary_type;
pub mod release_group_secondary_type_join;
pub mod release_group_tag;
pub mod release_group_tag_raw;
pub mod release_label;
pub mod release_meta;
pub mod release_packaging;
pub mod release_raw;
pub mod release_status;
pub mod release_tag;
pub mod release_tag_raw;
pub mod release_unknown_country;
pub mod replication_control;
pub mod script;
pub mod sea_orm_active_enums;
pub mod series;
pub mod series_alias;
pub mod series_alias_type;
pub mod series_annotation;
pub mod series_attribute;
pub mod series_attribute_type;
pub mod series_attribute_type_allowed_value;
pub mod series_gid_redirect;
pub mod series_ordering_type;
pub mod series_tag;
pub mod series_tag_raw;
pub mod series_type;
pub mod tag;
pub mod tag_relation;
pub mod track;
pub mod track_gid_redirect;
pub mod track_raw;
pub mod unreferenced_row_log;
pub mod url;
pub mod url_gid_redirect;
pub mod vote;
pub mod work;
pub mod work_alias;
pub mod work_alias_type;
pub mod work_annotation;
pub mod work_attribute;
pub mod work_attribute_type;
pub mod work_attribute_type_allowed_value;
pub mod work_gid_redirect;
pub mod work_language;
pub mod work_meta;
pub mod work_rating_raw;
pub mod work_tag;
pub mod work_tag_raw;
pub mod work_type;

seaography::register_entity_modules!([
    alternative_medium,
    alternative_medium_track,
    alternative_release,
    alternative_release_type,
    alternative_track,
    annotation,
    application,
    area,
    area_alias,
    area_alias_type,
    area_annotation,
    area_attribute,
    area_attribute_type,
    area_attribute_type_allowed_value,
    area_gid_redirect,
    area_tag,
    area_tag_raw,
    area_type,
    artist,
    artist_alias,
    artist_alias_type,
    artist_annotation,
    artist_attribute,
    artist_attribute_type,
    artist_attribute_type_allowed_value,
    artist_credit,
    artist_credit_gid_redirect,
    artist_credit_name,
    artist_gid_redirect,
    artist_ipi,
    artist_isni,
    artist_meta,
    artist_rating_raw,
    artist_release_group_pending_update,
    artist_release_pending_update,
    artist_tag,
    artist_tag_raw,
    artist_type,
    autoeditor_election,
    autoeditor_election_vote,
    cdtoc,
    cdtoc_raw,
    country_area,
    deleted_entity,
    edit,
    edit_area,
    edit_artist,
    edit_data,
    edit_event,
    edit_genre,
    edit_instrument,
    edit_label,
    edit_mood,
    edit_note,
    edit_note_change,
    edit_note_recipient,
    edit_place,
    edit_recording,
    edit_release,
    edit_release_group,
    edit_series,
    edit_url,
    edit_work,
    editor,
    editor_collection,
    editor_collection_area,
    editor_collection_artist,
    editor_collection_collaborator,
    editor_collection_deleted_entity,
    editor_collection_event,
    editor_collection_genre,
    editor_collection_gid_redirect,
    editor_collection_instrument,
    editor_collection_label,
    editor_collection_place,
    editor_collection_recording,
    editor_collection_release,
    editor_collection_release_group,
    editor_collection_series,
    editor_collection_type,
    editor_collection_work,
    editor_language,
    editor_oauth_token,
    editor_preference,
    editor_subscribe_artist,
    editor_subscribe_artist_deleted,
    editor_subscribe_collection,
    editor_subscribe_editor,
    editor_subscribe_label,
    editor_subscribe_label_deleted,
    editor_subscribe_series,
    editor_subscribe_series_deleted,
    event,
    event_alias,
    event_alias_type,
    event_annotation,
    event_attribute,
    event_attribute_type,
    event_attribute_type_allowed_value,
    event_gid_redirect,
    event_meta,
    event_rating_raw,
    event_tag,
    event_tag_raw,
    event_type,
    gender,
    genre,
    genre_alias,
    genre_alias_type,
    genre_annotation,
    instrument,
    instrument_alias,
    instrument_alias_type,
    instrument_annotation,
    instrument_attribute,
    instrument_attribute_type,
    instrument_attribute_type_allowed_value,
    instrument_gid_redirect,
    instrument_tag,
    instrument_tag_raw,
    instrument_type,
    iso_3166_1,
    iso_3166_2,
    iso_3166_3,
    isrc,
    iswc,
    l_area_area,
    l_area_artist,
    l_area_event,
    l_area_genre,
    l_area_instrument,
    l_area_label,
    l_area_mood,
    l_area_place,
    l_area_recording,
    l_area_release,
    l_area_release_group,
    l_area_series,
    l_area_url,
    l_area_work,
    l_artist_artist,
    l_artist_event,
    l_artist_genre,
    l_artist_instrument,
    l_artist_label,
    l_artist_mood,
    l_artist_place,
    l_artist_recording,
    l_artist_release,
    l_artist_release_group,
    l_artist_series,
    l_artist_url,
    l_artist_work,
    l_event_event,
    l_event_genre,
    l_event_instrument,
    l_event_label,
    l_event_mood,
    l_event_place,
    l_event_recording,
    l_event_release,
    l_event_release_group,
    l_event_series,
    l_event_url,
    l_event_work,
    l_genre_genre,
    l_genre_instrument,
    l_genre_label,
    l_genre_mood,
    l_genre_place,
    l_genre_recording,
    l_genre_release,
    l_genre_release_group,
    l_genre_series,
    l_genre_url,
    l_genre_work,
    l_instrument_instrument,
    l_instrument_label,
    l_instrument_mood,
    l_instrument_place,
    l_instrument_recording,
    l_instrument_release,
    l_instrument_release_group,
    l_instrument_series,
    l_instrument_url,
    l_instrument_work,
    l_label_label,
    l_label_mood,
    l_label_place,
    l_label_recording,
    l_label_release,
    l_label_release_group,
    l_label_series,
    l_label_url,
    l_label_work,
    l_mood_mood,
    l_mood_place,
    l_mood_recording,
    l_mood_release,
    l_mood_release_group,
    l_mood_series,
    l_mood_url,
    l_mood_work,
    l_place_place,
    l_place_recording,
    l_place_release,
    l_place_release_group,
    l_place_series,
    l_place_url,
    l_place_work,
    l_recording_recording,
    l_recording_release,
    l_recording_release_group,
    l_recording_series,
    l_recording_url,
    l_recording_work,
    l_release_group_release_group,
    l_release_group_series,
    l_release_group_url,
    l_release_group_work,
    l_release_release,
    l_release_release_group,
    l_release_series,
    l_release_url,
    l_release_work,
    l_series_series,
    l_series_url,
    l_series_work,
    l_url_url,
    l_url_work,
    l_work_work,
    label,
    label_alias,
    label_alias_type,
    label_annotation,
    label_attribute,
    label_attribute_type,
    label_attribute_type_allowed_value,
    label_gid_redirect,
    label_ipi,
    label_isni,
    label_meta,
    label_rating_raw,
    label_tag,
    label_tag_raw,
    label_type,
    language,
    link,
    link_attribute,
    link_attribute_credit,
    link_attribute_text_value,
    link_attribute_type,
    link_creditable_attribute_type,
    link_text_attribute_type,
    link_type,
    link_type_attribute_type,
    medium,
    medium_attribute,
    medium_attribute_type,
    medium_attribute_type_allowed_format,
    medium_attribute_type_allowed_value,
    medium_attribute_type_allowed_value_allowed_format,
    medium_cdtoc,
    medium_format,
    medium_gid_redirect,
    mood,
    mood_alias,
    mood_alias_type,
    mood_annotation,
    old_editor_name,
    orderable_link_type,
    place,
    place_alias,
    place_alias_type,
    place_annotation,
    place_attribute,
    place_attribute_type,
    place_attribute_type_allowed_value,
    place_gid_redirect,
    place_meta,
    place_rating_raw,
    place_tag,
    place_tag_raw,
    place_type,
    recording,
    recording_alias,
    recording_alias_type,
    recording_annotation,
    recording_attribute,
    recording_attribute_type,
    recording_attribute_type_allowed_value,
    recording_gid_redirect,
    recording_meta,
    recording_rating_raw,
    recording_tag,
    recording_tag_raw,
    release,
    release_alias,
    release_alias_type,
    release_annotation,
    release_attribute,
    release_attribute_type,
    release_attribute_type_allowed_value,
    release_country,
    release_gid_redirect,
    release_group,
    release_group_alias,
    release_group_alias_type,
    release_group_annotation,
    release_group_attribute,
    release_group_attribute_type,
    release_group_attribute_type_allowed_value,
    release_group_gid_redirect,
    release_group_meta,
    release_group_primary_type,
    release_group_rating_raw,
    release_group_secondary_type,
    release_group_secondary_type_join,
    release_group_tag,
    release_group_tag_raw,
    release_label,
    release_meta,
    release_packaging,
    release_raw,
    release_status,
    release_tag,
    release_tag_raw,
    release_unknown_country,
    replication_control,
    script,
    series,
    series_alias,
    series_alias_type,
    series_annotation,
    series_attribute,
    series_attribute_type,
    series_attribute_type_allowed_value,
    series_gid_redirect,
    series_ordering_type,
    series_tag,
    series_tag_raw,
    series_type,
    tag,
    tag_relation,
    track,
    track_gid_redirect,
    track_raw,
    unreferenced_row_log,
    url,
    url_gid_redirect,
    vote,
    work,
    work_alias,
    work_alias_type,
    work_annotation,
    work_attribute,
    work_attribute_type,
    work_attribute_type_allowed_value,
    work_gid_redirect,
    work_language,
    work_meta,
    work_rating_raw,
    work_tag,
    work_tag_raw,
    work_type,
]);
seaography::register_active_enums!([
    sea_orm_active_enums::CoverArtPresence,
    sea_orm_active_enums::EditNoteStatus,
    sea_orm_active_enums::EventArtPresence,
    sea_orm_active_enums::Fluency,
    sea_orm_active_enums::OauthCodeChallengeMethod,
]);
