//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "link")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub link_type: i32,
    pub begin_date_year: Option<i16>,
    pub begin_date_month: Option<i16>,
    pub begin_date_day: Option<i16>,
    pub end_date_year: Option<i16>,
    pub end_date_month: Option<i16>,
    pub end_date_day: Option<i16>,
    pub attribute_count: i32,
    pub created: Option<DateTimeWithTimeZone>,
    pub ended: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::l_area_area::Entity")]
    LAreaArea,
    #[sea_orm(has_many = "super::l_area_artist::Entity")]
    LAreaArtist,
    #[sea_orm(has_many = "super::l_area_event::Entity")]
    LAreaEvent,
    #[sea_orm(has_many = "super::l_area_genre::Entity")]
    LAreaGenre,
    #[sea_orm(has_many = "super::l_area_instrument::Entity")]
    LAreaInstrument,
    #[sea_orm(has_many = "super::l_area_label::Entity")]
    LAreaLabel,
    #[sea_orm(has_many = "super::l_area_mood::Entity")]
    LAreaMood,
    #[sea_orm(has_many = "super::l_area_place::Entity")]
    LAreaPlace,
    #[sea_orm(has_many = "super::l_area_recording::Entity")]
    LAreaRecording,
    #[sea_orm(has_many = "super::l_area_release::Entity")]
    LAreaRelease,
    #[sea_orm(has_many = "super::l_area_release_group::Entity")]
    LAreaReleaseGroup,
    #[sea_orm(has_many = "super::l_area_series::Entity")]
    LAreaSeries,
    #[sea_orm(has_many = "super::l_area_url::Entity")]
    LAreaUrl,
    #[sea_orm(has_many = "super::l_area_work::Entity")]
    LAreaWork,
    #[sea_orm(has_many = "super::l_artist_artist::Entity")]
    LArtistArtist,
    #[sea_orm(has_many = "super::l_artist_event::Entity")]
    LArtistEvent,
    #[sea_orm(has_many = "super::l_artist_genre::Entity")]
    LArtistGenre,
    #[sea_orm(has_many = "super::l_artist_instrument::Entity")]
    LArtistInstrument,
    #[sea_orm(has_many = "super::l_artist_label::Entity")]
    LArtistLabel,
    #[sea_orm(has_many = "super::l_artist_mood::Entity")]
    LArtistMood,
    #[sea_orm(has_many = "super::l_artist_place::Entity")]
    LArtistPlace,
    #[sea_orm(has_many = "super::l_artist_recording::Entity")]
    LArtistRecording,
    #[sea_orm(has_many = "super::l_artist_release::Entity")]
    LArtistRelease,
    #[sea_orm(has_many = "super::l_artist_release_group::Entity")]
    LArtistReleaseGroup,
    #[sea_orm(has_many = "super::l_artist_series::Entity")]
    LArtistSeries,
    #[sea_orm(has_many = "super::l_artist_url::Entity")]
    LArtistUrl,
    #[sea_orm(has_many = "super::l_artist_work::Entity")]
    LArtistWork,
    #[sea_orm(has_many = "super::l_event_event::Entity")]
    LEventEvent,
    #[sea_orm(has_many = "super::l_event_genre::Entity")]
    LEventGenre,
    #[sea_orm(has_many = "super::l_event_instrument::Entity")]
    LEventInstrument,
    #[sea_orm(has_many = "super::l_event_label::Entity")]
    LEventLabel,
    #[sea_orm(has_many = "super::l_event_mood::Entity")]
    LEventMood,
    #[sea_orm(has_many = "super::l_event_place::Entity")]
    LEventPlace,
    #[sea_orm(has_many = "super::l_event_recording::Entity")]
    LEventRecording,
    #[sea_orm(has_many = "super::l_event_release::Entity")]
    LEventRelease,
    #[sea_orm(has_many = "super::l_event_release_group::Entity")]
    LEventReleaseGroup,
    #[sea_orm(has_many = "super::l_event_series::Entity")]
    LEventSeries,
    #[sea_orm(has_many = "super::l_event_url::Entity")]
    LEventUrl,
    #[sea_orm(has_many = "super::l_event_work::Entity")]
    LEventWork,
    #[sea_orm(has_many = "super::l_genre_genre::Entity")]
    LGenreGenre,
    #[sea_orm(has_many = "super::l_genre_instrument::Entity")]
    LGenreInstrument,
    #[sea_orm(has_many = "super::l_genre_label::Entity")]
    LGenreLabel,
    #[sea_orm(has_many = "super::l_genre_mood::Entity")]
    LGenreMood,
    #[sea_orm(has_many = "super::l_genre_place::Entity")]
    LGenrePlace,
    #[sea_orm(has_many = "super::l_genre_recording::Entity")]
    LGenreRecording,
    #[sea_orm(has_many = "super::l_genre_release::Entity")]
    LGenreRelease,
    #[sea_orm(has_many = "super::l_genre_release_group::Entity")]
    LGenreReleaseGroup,
    #[sea_orm(has_many = "super::l_genre_series::Entity")]
    LGenreSeries,
    #[sea_orm(has_many = "super::l_genre_url::Entity")]
    LGenreUrl,
    #[sea_orm(has_many = "super::l_genre_work::Entity")]
    LGenreWork,
    #[sea_orm(has_many = "super::l_instrument_instrument::Entity")]
    LInstrumentInstrument,
    #[sea_orm(has_many = "super::l_instrument_label::Entity")]
    LInstrumentLabel,
    #[sea_orm(has_many = "super::l_instrument_mood::Entity")]
    LInstrumentMood,
    #[sea_orm(has_many = "super::l_instrument_place::Entity")]
    LInstrumentPlace,
    #[sea_orm(has_many = "super::l_instrument_recording::Entity")]
    LInstrumentRecording,
    #[sea_orm(has_many = "super::l_instrument_release::Entity")]
    LInstrumentRelease,
    #[sea_orm(has_many = "super::l_instrument_release_group::Entity")]
    LInstrumentReleaseGroup,
    #[sea_orm(has_many = "super::l_instrument_series::Entity")]
    LInstrumentSeries,
    #[sea_orm(has_many = "super::l_instrument_url::Entity")]
    LInstrumentUrl,
    #[sea_orm(has_many = "super::l_instrument_work::Entity")]
    LInstrumentWork,
    #[sea_orm(has_many = "super::l_label_label::Entity")]
    LLabelLabel,
    #[sea_orm(has_many = "super::l_label_mood::Entity")]
    LLabelMood,
    #[sea_orm(has_many = "super::l_label_place::Entity")]
    LLabelPlace,
    #[sea_orm(has_many = "super::l_label_recording::Entity")]
    LLabelRecording,
    #[sea_orm(has_many = "super::l_label_release::Entity")]
    LLabelRelease,
    #[sea_orm(has_many = "super::l_label_release_group::Entity")]
    LLabelReleaseGroup,
    #[sea_orm(has_many = "super::l_label_series::Entity")]
    LLabelSeries,
    #[sea_orm(has_many = "super::l_label_url::Entity")]
    LLabelUrl,
    #[sea_orm(has_many = "super::l_label_work::Entity")]
    LLabelWork,
    #[sea_orm(has_many = "super::l_mood_mood::Entity")]
    LMoodMood,
    #[sea_orm(has_many = "super::l_mood_place::Entity")]
    LMoodPlace,
    #[sea_orm(has_many = "super::l_mood_recording::Entity")]
    LMoodRecording,
    #[sea_orm(has_many = "super::l_mood_release::Entity")]
    LMoodRelease,
    #[sea_orm(has_many = "super::l_mood_release_group::Entity")]
    LMoodReleaseGroup,
    #[sea_orm(has_many = "super::l_mood_series::Entity")]
    LMoodSeries,
    #[sea_orm(has_many = "super::l_mood_url::Entity")]
    LMoodUrl,
    #[sea_orm(has_many = "super::l_mood_work::Entity")]
    LMoodWork,
    #[sea_orm(has_many = "super::l_place_place::Entity")]
    LPlacePlace,
    #[sea_orm(has_many = "super::l_place_recording::Entity")]
    LPlaceRecording,
    #[sea_orm(has_many = "super::l_place_release::Entity")]
    LPlaceRelease,
    #[sea_orm(has_many = "super::l_place_release_group::Entity")]
    LPlaceReleaseGroup,
    #[sea_orm(has_many = "super::l_place_series::Entity")]
    LPlaceSeries,
    #[sea_orm(has_many = "super::l_place_url::Entity")]
    LPlaceUrl,
    #[sea_orm(has_many = "super::l_place_work::Entity")]
    LPlaceWork,
    #[sea_orm(has_many = "super::l_recording_recording::Entity")]
    LRecordingRecording,
    #[sea_orm(has_many = "super::l_recording_release::Entity")]
    LRecordingRelease,
    #[sea_orm(has_many = "super::l_recording_release_group::Entity")]
    LRecordingReleaseGroup,
    #[sea_orm(has_many = "super::l_recording_series::Entity")]
    LRecordingSeries,
    #[sea_orm(has_many = "super::l_recording_url::Entity")]
    LRecordingUrl,
    #[sea_orm(has_many = "super::l_recording_work::Entity")]
    LRecordingWork,
    #[sea_orm(has_many = "super::l_release_group_release_group::Entity")]
    LReleaseGroupReleaseGroup,
    #[sea_orm(has_many = "super::l_release_group_series::Entity")]
    LReleaseGroupSeries,
    #[sea_orm(has_many = "super::l_release_group_url::Entity")]
    LReleaseGroupUrl,
    #[sea_orm(has_many = "super::l_release_group_work::Entity")]
    LReleaseGroupWork,
    #[sea_orm(has_many = "super::l_release_release::Entity")]
    LReleaseRelease,
    #[sea_orm(has_many = "super::l_release_release_group::Entity")]
    LReleaseReleaseGroup,
    #[sea_orm(has_many = "super::l_release_series::Entity")]
    LReleaseSeries,
    #[sea_orm(has_many = "super::l_release_url::Entity")]
    LReleaseUrl,
    #[sea_orm(has_many = "super::l_release_work::Entity")]
    LReleaseWork,
    #[sea_orm(has_many = "super::l_series_series::Entity")]
    LSeriesSeries,
    #[sea_orm(has_many = "super::l_series_url::Entity")]
    LSeriesUrl,
    #[sea_orm(has_many = "super::l_series_work::Entity")]
    LSeriesWork,
    #[sea_orm(has_many = "super::l_url_url::Entity")]
    LUrlUrl,
    #[sea_orm(has_many = "super::l_url_work::Entity")]
    LUrlWork,
    #[sea_orm(has_many = "super::l_work_work::Entity")]
    LWorkWork,
    #[sea_orm(has_many = "super::link_attribute::Entity")]
    LinkAttribute,
    #[sea_orm(has_many = "super::link_attribute_credit::Entity")]
    LinkAttributeCredit,
    #[sea_orm(has_many = "super::link_attribute_text_value::Entity")]
    LinkAttributeTextValue,
    #[sea_orm(
        belongs_to = "super::link_type::Entity",
        from = "Column::LinkType",
        to = "super::link_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    LinkType,
}

impl Related<super::l_area_area::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaArea.def()
    }
}

impl Related<super::l_area_artist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaArtist.def()
    }
}

impl Related<super::l_area_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaEvent.def()
    }
}

impl Related<super::l_area_genre::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaGenre.def()
    }
}

impl Related<super::l_area_instrument::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaInstrument.def()
    }
}

impl Related<super::l_area_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaLabel.def()
    }
}

impl Related<super::l_area_mood::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaMood.def()
    }
}

impl Related<super::l_area_place::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaPlace.def()
    }
}

impl Related<super::l_area_recording::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaRecording.def()
    }
}

impl Related<super::l_area_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaRelease.def()
    }
}

impl Related<super::l_area_release_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaReleaseGroup.def()
    }
}

impl Related<super::l_area_series::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaSeries.def()
    }
}

impl Related<super::l_area_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaUrl.def()
    }
}

impl Related<super::l_area_work::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaWork.def()
    }
}

impl Related<super::l_artist_artist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistArtist.def()
    }
}

impl Related<super::l_artist_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistEvent.def()
    }
}

impl Related<super::l_artist_genre::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistGenre.def()
    }
}

impl Related<super::l_artist_instrument::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistInstrument.def()
    }
}

impl Related<super::l_artist_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistLabel.def()
    }
}

impl Related<super::l_artist_mood::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistMood.def()
    }
}

impl Related<super::l_artist_place::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistPlace.def()
    }
}

impl Related<super::l_artist_recording::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistRecording.def()
    }
}

impl Related<super::l_artist_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistRelease.def()
    }
}

impl Related<super::l_artist_release_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistReleaseGroup.def()
    }
}

impl Related<super::l_artist_series::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistSeries.def()
    }
}

impl Related<super::l_artist_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistUrl.def()
    }
}

impl Related<super::l_artist_work::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistWork.def()
    }
}

impl Related<super::l_event_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LEventEvent.def()
    }
}

impl Related<super::l_event_genre::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LEventGenre.def()
    }
}

impl Related<super::l_event_instrument::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LEventInstrument.def()
    }
}

impl Related<super::l_event_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LEventLabel.def()
    }
}

impl Related<super::l_event_mood::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LEventMood.def()
    }
}

impl Related<super::l_event_place::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LEventPlace.def()
    }
}

impl Related<super::l_event_recording::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LEventRecording.def()
    }
}

impl Related<super::l_event_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LEventRelease.def()
    }
}

impl Related<super::l_event_release_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LEventReleaseGroup.def()
    }
}

impl Related<super::l_event_series::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LEventSeries.def()
    }
}

impl Related<super::l_event_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LEventUrl.def()
    }
}

impl Related<super::l_event_work::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LEventWork.def()
    }
}

impl Related<super::l_genre_genre::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LGenreGenre.def()
    }
}

impl Related<super::l_genre_instrument::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LGenreInstrument.def()
    }
}

impl Related<super::l_genre_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LGenreLabel.def()
    }
}

impl Related<super::l_genre_mood::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LGenreMood.def()
    }
}

impl Related<super::l_genre_place::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LGenrePlace.def()
    }
}

impl Related<super::l_genre_recording::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LGenreRecording.def()
    }
}

impl Related<super::l_genre_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LGenreRelease.def()
    }
}

impl Related<super::l_genre_release_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LGenreReleaseGroup.def()
    }
}

impl Related<super::l_genre_series::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LGenreSeries.def()
    }
}

impl Related<super::l_genre_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LGenreUrl.def()
    }
}

impl Related<super::l_genre_work::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LGenreWork.def()
    }
}

impl Related<super::l_instrument_instrument::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LInstrumentInstrument.def()
    }
}

impl Related<super::l_instrument_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LInstrumentLabel.def()
    }
}

impl Related<super::l_instrument_mood::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LInstrumentMood.def()
    }
}

impl Related<super::l_instrument_place::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LInstrumentPlace.def()
    }
}

impl Related<super::l_instrument_recording::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LInstrumentRecording.def()
    }
}

impl Related<super::l_instrument_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LInstrumentRelease.def()
    }
}

impl Related<super::l_instrument_release_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LInstrumentReleaseGroup.def()
    }
}

impl Related<super::l_instrument_series::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LInstrumentSeries.def()
    }
}

impl Related<super::l_instrument_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LInstrumentUrl.def()
    }
}

impl Related<super::l_instrument_work::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LInstrumentWork.def()
    }
}

impl Related<super::l_label_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LLabelLabel.def()
    }
}

impl Related<super::l_label_mood::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LLabelMood.def()
    }
}

impl Related<super::l_label_place::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LLabelPlace.def()
    }
}

impl Related<super::l_label_recording::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LLabelRecording.def()
    }
}

impl Related<super::l_label_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LLabelRelease.def()
    }
}

impl Related<super::l_label_release_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LLabelReleaseGroup.def()
    }
}

impl Related<super::l_label_series::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LLabelSeries.def()
    }
}

impl Related<super::l_label_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LLabelUrl.def()
    }
}

impl Related<super::l_label_work::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LLabelWork.def()
    }
}

impl Related<super::l_mood_mood::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LMoodMood.def()
    }
}

impl Related<super::l_mood_place::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LMoodPlace.def()
    }
}

impl Related<super::l_mood_recording::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LMoodRecording.def()
    }
}

impl Related<super::l_mood_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LMoodRelease.def()
    }
}

impl Related<super::l_mood_release_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LMoodReleaseGroup.def()
    }
}

impl Related<super::l_mood_series::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LMoodSeries.def()
    }
}

impl Related<super::l_mood_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LMoodUrl.def()
    }
}

impl Related<super::l_mood_work::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LMoodWork.def()
    }
}

impl Related<super::l_place_place::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LPlacePlace.def()
    }
}

impl Related<super::l_place_recording::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LPlaceRecording.def()
    }
}

impl Related<super::l_place_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LPlaceRelease.def()
    }
}

impl Related<super::l_place_release_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LPlaceReleaseGroup.def()
    }
}

impl Related<super::l_place_series::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LPlaceSeries.def()
    }
}

impl Related<super::l_place_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LPlaceUrl.def()
    }
}

impl Related<super::l_place_work::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LPlaceWork.def()
    }
}

impl Related<super::l_recording_recording::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LRecordingRecording.def()
    }
}

impl Related<super::l_recording_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LRecordingRelease.def()
    }
}

impl Related<super::l_recording_release_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LRecordingReleaseGroup.def()
    }
}

impl Related<super::l_recording_series::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LRecordingSeries.def()
    }
}

impl Related<super::l_recording_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LRecordingUrl.def()
    }
}

impl Related<super::l_recording_work::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LRecordingWork.def()
    }
}

impl Related<super::l_release_group_release_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LReleaseGroupReleaseGroup.def()
    }
}

impl Related<super::l_release_group_series::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LReleaseGroupSeries.def()
    }
}

impl Related<super::l_release_group_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LReleaseGroupUrl.def()
    }
}

impl Related<super::l_release_group_work::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LReleaseGroupWork.def()
    }
}

impl Related<super::l_release_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LReleaseRelease.def()
    }
}

impl Related<super::l_release_release_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LReleaseReleaseGroup.def()
    }
}

impl Related<super::l_release_series::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LReleaseSeries.def()
    }
}

impl Related<super::l_release_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LReleaseUrl.def()
    }
}

impl Related<super::l_release_work::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LReleaseWork.def()
    }
}

impl Related<super::l_series_series::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LSeriesSeries.def()
    }
}

impl Related<super::l_series_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LSeriesUrl.def()
    }
}

impl Related<super::l_series_work::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LSeriesWork.def()
    }
}

impl Related<super::l_url_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LUrlUrl.def()
    }
}

impl Related<super::l_url_work::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LUrlWork.def()
    }
}

impl Related<super::l_work_work::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LWorkWork.def()
    }
}

impl Related<super::link_attribute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LinkAttribute.def()
    }
}

impl Related<super::link_attribute_credit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LinkAttributeCredit.def()
    }
}

impl Related<super::link_attribute_text_value::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LinkAttributeTextValue.def()
    }
}

impl Related<super::link_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LinkType.def()
    }
}

impl Related<super::link_attribute_type::Entity> for Entity {
    fn to() -> RelationDef {
        super::link_attribute::Relation::LinkAttributeType.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::link_attribute::Relation::Link.def().rev())
    }
}

impl Related<super::link_creditable_attribute_type::Entity> for Entity {
    fn to() -> RelationDef {
        super::link_attribute_credit::Relation::LinkCreditableAttributeType.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::link_attribute_credit::Relation::Link.def().rev())
    }
}

impl Related<super::link_text_attribute_type::Entity> for Entity {
    fn to() -> RelationDef {
        super::link_attribute_text_value::Relation::LinkTextAttributeType.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::link_attribute_text_value::Relation::Link.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::l_area_area::Entity")]
    LAreaArea,
    #[sea_orm(entity = "super::l_area_artist::Entity")]
    LAreaArtist,
    #[sea_orm(entity = "super::l_area_event::Entity")]
    LAreaEvent,
    #[sea_orm(entity = "super::l_area_genre::Entity")]
    LAreaGenre,
    #[sea_orm(entity = "super::l_area_instrument::Entity")]
    LAreaInstrument,
    #[sea_orm(entity = "super::l_area_label::Entity")]
    LAreaLabel,
    #[sea_orm(entity = "super::l_area_mood::Entity")]
    LAreaMood,
    #[sea_orm(entity = "super::l_area_place::Entity")]
    LAreaPlace,
    #[sea_orm(entity = "super::l_area_recording::Entity")]
    LAreaRecording,
    #[sea_orm(entity = "super::l_area_release::Entity")]
    LAreaRelease,
    #[sea_orm(entity = "super::l_area_release_group::Entity")]
    LAreaReleaseGroup,
    #[sea_orm(entity = "super::l_area_series::Entity")]
    LAreaSeries,
    #[sea_orm(entity = "super::l_area_url::Entity")]
    LAreaUrl,
    #[sea_orm(entity = "super::l_area_work::Entity")]
    LAreaWork,
    #[sea_orm(entity = "super::l_artist_artist::Entity")]
    LArtistArtist,
    #[sea_orm(entity = "super::l_artist_event::Entity")]
    LArtistEvent,
    #[sea_orm(entity = "super::l_artist_genre::Entity")]
    LArtistGenre,
    #[sea_orm(entity = "super::l_artist_instrument::Entity")]
    LArtistInstrument,
    #[sea_orm(entity = "super::l_artist_label::Entity")]
    LArtistLabel,
    #[sea_orm(entity = "super::l_artist_mood::Entity")]
    LArtistMood,
    #[sea_orm(entity = "super::l_artist_place::Entity")]
    LArtistPlace,
    #[sea_orm(entity = "super::l_artist_recording::Entity")]
    LArtistRecording,
    #[sea_orm(entity = "super::l_artist_release::Entity")]
    LArtistRelease,
    #[sea_orm(entity = "super::l_artist_release_group::Entity")]
    LArtistReleaseGroup,
    #[sea_orm(entity = "super::l_artist_series::Entity")]
    LArtistSeries,
    #[sea_orm(entity = "super::l_artist_url::Entity")]
    LArtistUrl,
    #[sea_orm(entity = "super::l_artist_work::Entity")]
    LArtistWork,
    #[sea_orm(entity = "super::l_event_event::Entity")]
    LEventEvent,
    #[sea_orm(entity = "super::l_event_genre::Entity")]
    LEventGenre,
    #[sea_orm(entity = "super::l_event_instrument::Entity")]
    LEventInstrument,
    #[sea_orm(entity = "super::l_event_label::Entity")]
    LEventLabel,
    #[sea_orm(entity = "super::l_event_mood::Entity")]
    LEventMood,
    #[sea_orm(entity = "super::l_event_place::Entity")]
    LEventPlace,
    #[sea_orm(entity = "super::l_event_recording::Entity")]
    LEventRecording,
    #[sea_orm(entity = "super::l_event_release::Entity")]
    LEventRelease,
    #[sea_orm(entity = "super::l_event_release_group::Entity")]
    LEventReleaseGroup,
    #[sea_orm(entity = "super::l_event_series::Entity")]
    LEventSeries,
    #[sea_orm(entity = "super::l_event_url::Entity")]
    LEventUrl,
    #[sea_orm(entity = "super::l_event_work::Entity")]
    LEventWork,
    #[sea_orm(entity = "super::l_genre_genre::Entity")]
    LGenreGenre,
    #[sea_orm(entity = "super::l_genre_instrument::Entity")]
    LGenreInstrument,
    #[sea_orm(entity = "super::l_genre_label::Entity")]
    LGenreLabel,
    #[sea_orm(entity = "super::l_genre_mood::Entity")]
    LGenreMood,
    #[sea_orm(entity = "super::l_genre_place::Entity")]
    LGenrePlace,
    #[sea_orm(entity = "super::l_genre_recording::Entity")]
    LGenreRecording,
    #[sea_orm(entity = "super::l_genre_release::Entity")]
    LGenreRelease,
    #[sea_orm(entity = "super::l_genre_release_group::Entity")]
    LGenreReleaseGroup,
    #[sea_orm(entity = "super::l_genre_series::Entity")]
    LGenreSeries,
    #[sea_orm(entity = "super::l_genre_url::Entity")]
    LGenreUrl,
    #[sea_orm(entity = "super::l_genre_work::Entity")]
    LGenreWork,
    #[sea_orm(entity = "super::l_instrument_instrument::Entity")]
    LInstrumentInstrument,
    #[sea_orm(entity = "super::l_instrument_label::Entity")]
    LInstrumentLabel,
    #[sea_orm(entity = "super::l_instrument_mood::Entity")]
    LInstrumentMood,
    #[sea_orm(entity = "super::l_instrument_place::Entity")]
    LInstrumentPlace,
    #[sea_orm(entity = "super::l_instrument_recording::Entity")]
    LInstrumentRecording,
    #[sea_orm(entity = "super::l_instrument_release::Entity")]
    LInstrumentRelease,
    #[sea_orm(entity = "super::l_instrument_release_group::Entity")]
    LInstrumentReleaseGroup,
    #[sea_orm(entity = "super::l_instrument_series::Entity")]
    LInstrumentSeries,
    #[sea_orm(entity = "super::l_instrument_url::Entity")]
    LInstrumentUrl,
    #[sea_orm(entity = "super::l_instrument_work::Entity")]
    LInstrumentWork,
    #[sea_orm(entity = "super::l_label_label::Entity")]
    LLabelLabel,
    #[sea_orm(entity = "super::l_label_mood::Entity")]
    LLabelMood,
    #[sea_orm(entity = "super::l_label_place::Entity")]
    LLabelPlace,
    #[sea_orm(entity = "super::l_label_recording::Entity")]
    LLabelRecording,
    #[sea_orm(entity = "super::l_label_release::Entity")]
    LLabelRelease,
    #[sea_orm(entity = "super::l_label_release_group::Entity")]
    LLabelReleaseGroup,
    #[sea_orm(entity = "super::l_label_series::Entity")]
    LLabelSeries,
    #[sea_orm(entity = "super::l_label_url::Entity")]
    LLabelUrl,
    #[sea_orm(entity = "super::l_label_work::Entity")]
    LLabelWork,
    #[sea_orm(entity = "super::l_mood_mood::Entity")]
    LMoodMood,
    #[sea_orm(entity = "super::l_mood_place::Entity")]
    LMoodPlace,
    #[sea_orm(entity = "super::l_mood_recording::Entity")]
    LMoodRecording,
    #[sea_orm(entity = "super::l_mood_release::Entity")]
    LMoodRelease,
    #[sea_orm(entity = "super::l_mood_release_group::Entity")]
    LMoodReleaseGroup,
    #[sea_orm(entity = "super::l_mood_series::Entity")]
    LMoodSeries,
    #[sea_orm(entity = "super::l_mood_url::Entity")]
    LMoodUrl,
    #[sea_orm(entity = "super::l_mood_work::Entity")]
    LMoodWork,
    #[sea_orm(entity = "super::l_place_place::Entity")]
    LPlacePlace,
    #[sea_orm(entity = "super::l_place_recording::Entity")]
    LPlaceRecording,
    #[sea_orm(entity = "super::l_place_release::Entity")]
    LPlaceRelease,
    #[sea_orm(entity = "super::l_place_release_group::Entity")]
    LPlaceReleaseGroup,
    #[sea_orm(entity = "super::l_place_series::Entity")]
    LPlaceSeries,
    #[sea_orm(entity = "super::l_place_url::Entity")]
    LPlaceUrl,
    #[sea_orm(entity = "super::l_place_work::Entity")]
    LPlaceWork,
    #[sea_orm(entity = "super::l_recording_recording::Entity")]
    LRecordingRecording,
    #[sea_orm(entity = "super::l_recording_release::Entity")]
    LRecordingRelease,
    #[sea_orm(entity = "super::l_recording_release_group::Entity")]
    LRecordingReleaseGroup,
    #[sea_orm(entity = "super::l_recording_series::Entity")]
    LRecordingSeries,
    #[sea_orm(entity = "super::l_recording_url::Entity")]
    LRecordingUrl,
    #[sea_orm(entity = "super::l_recording_work::Entity")]
    LRecordingWork,
    #[sea_orm(entity = "super::l_release_group_release_group::Entity")]
    LReleaseGroupReleaseGroup,
    #[sea_orm(entity = "super::l_release_group_series::Entity")]
    LReleaseGroupSeries,
    #[sea_orm(entity = "super::l_release_group_url::Entity")]
    LReleaseGroupUrl,
    #[sea_orm(entity = "super::l_release_group_work::Entity")]
    LReleaseGroupWork,
    #[sea_orm(entity = "super::l_release_release::Entity")]
    LReleaseRelease,
    #[sea_orm(entity = "super::l_release_release_group::Entity")]
    LReleaseReleaseGroup,
    #[sea_orm(entity = "super::l_release_series::Entity")]
    LReleaseSeries,
    #[sea_orm(entity = "super::l_release_url::Entity")]
    LReleaseUrl,
    #[sea_orm(entity = "super::l_release_work::Entity")]
    LReleaseWork,
    #[sea_orm(entity = "super::l_series_series::Entity")]
    LSeriesSeries,
    #[sea_orm(entity = "super::l_series_url::Entity")]
    LSeriesUrl,
    #[sea_orm(entity = "super::l_series_work::Entity")]
    LSeriesWork,
    #[sea_orm(entity = "super::l_url_url::Entity")]
    LUrlUrl,
    #[sea_orm(entity = "super::l_url_work::Entity")]
    LUrlWork,
    #[sea_orm(entity = "super::l_work_work::Entity")]
    LWorkWork,
    #[sea_orm(entity = "super::link_attribute::Entity")]
    LinkAttribute,
    #[sea_orm(entity = "super::link_attribute_credit::Entity")]
    LinkAttributeCredit,
    #[sea_orm(entity = "super::link_attribute_text_value::Entity")]
    LinkAttributeTextValue,
    #[sea_orm(entity = "super::link_type::Entity")]
    LinkType,
    #[sea_orm(entity = "super::link_attribute_type::Entity")]
    LinkAttributeType,
    #[sea_orm(entity = "super::link_creditable_attribute_type::Entity")]
    LinkCreditableAttributeType,
    #[sea_orm(entity = "super::link_text_attribute_type::Entity")]
    LinkTextAttributeType,
}
