//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "link_attribute_type")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub parent: Option<i32>,
    pub root: i32,
    pub child_order: i32,
    #[sea_orm(unique)]
    pub gid: Uuid,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub last_updated: Option<DateTimeWithTimeZone>,
}


impl ActiveModelBehavior for ActiveModel {}
