//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "link_type")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub parent: Option<i32>,
    pub child_order: i32,
    #[sea_orm(unique)]
    pub gid: Uuid,
    pub entity_type0: String,
    pub entity_type1: String,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub link_phrase: String,
    pub reverse_link_phrase: String,
    pub long_link_phrase: String,
    pub last_updated: Option<DateTimeWithTimeZone>,
    pub is_deprecated: bool,
    pub has_dates: bool,
    pub entity0_cardinality: i16,
    pub entity1_cardinality: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::link::Entity")]
    Link,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::Parent",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::link_type_attribute_type::Entity")]
    LinkTypeAttributeType,
    #[sea_orm(has_one = "super::orderable_link_type::Entity")]
    OrderableLinkType,
}

impl Related<super::link::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Link.def()
    }
}

impl Related<super::link_type_attribute_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LinkTypeAttributeType.def()
    }
}

impl Related<super::orderable_link_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderableLinkType.def()
    }
}

impl Related<super::link_attribute_type::Entity> for Entity {
    fn to() -> RelationDef {
        super::link_type_attribute_type::Relation::LinkAttributeType.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::link_type_attribute_type::Relation::LinkType
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::link::Entity")]
    Link,
    #[sea_orm(entity = "Entity", def = "Relation::SelfRef.def()")]
    SelfRef,
    #[sea_orm(entity = "super::link_type_attribute_type::Entity")]
    LinkTypeAttributeType,
    #[sea_orm(entity = "super::orderable_link_type::Entity")]
    OrderableLinkType,
    #[sea_orm(entity = "Entity", def = "Relation::SelfRef.def().rev()")]
    SelfRefReverse,
    #[sea_orm(entity = "super::link_attribute_type::Entity")]
    LinkAttributeType,
}
