//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "link_attribute_type")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub parent: Option<i32>,
    pub root: i32,
    pub child_order: i32,
    #[sea_orm(unique)]
    pub gid: Uuid,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub last_updated: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::link_attribute::Entity")]
    LinkAttribute,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::Parent",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef2,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::Root",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef1,
    #[sea_orm(has_one = "super::link_creditable_attribute_type::Entity")]
    LinkCreditableAttributeType,
    #[sea_orm(has_one = "super::link_text_attribute_type::Entity")]
    LinkTextAttributeType,
    #[sea_orm(has_many = "super::link_type_attribute_type::Entity")]
    LinkTypeAttributeType,
}

impl Related<super::link_attribute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LinkAttribute.def()
    }
}

impl Related<super::link_creditable_attribute_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LinkCreditableAttributeType.def()
    }
}

impl Related<super::link_text_attribute_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LinkTextAttributeType.def()
    }
}

impl Related<super::link_type_attribute_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LinkTypeAttributeType.def()
    }
}

impl Related<super::link::Entity> for Entity {
    fn to() -> RelationDef {
        super::link_attribute::Relation::Link.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::link_attribute::Relation::LinkAttributeType
                .def()
                .rev(),
        )
    }
}

impl Related<super::link_type::Entity> for Entity {
    fn to() -> RelationDef {
        super::link_type_attribute_type::Relation::LinkType.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::link_type_attribute_type::Relation::LinkAttributeType
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::link_attribute::Entity")]
    LinkAttribute,
    #[sea_orm(entity = "Entity", def = "Relation::SelfRef2.def()")]
    SelfRef2,
    #[sea_orm(entity = "Entity", def = "Relation::SelfRef1.def()")]
    SelfRef1,
    #[sea_orm(entity = "super::link_creditable_attribute_type::Entity")]
    LinkCreditableAttributeType,
    #[sea_orm(entity = "super::link_text_attribute_type::Entity")]
    LinkTextAttributeType,
    #[sea_orm(entity = "super::link_type_attribute_type::Entity")]
    LinkTypeAttributeType,
    #[sea_orm(entity = "Entity", def = "Relation::SelfRef2.def().rev()")]
    SelfRef2Reverse,
    #[sea_orm(entity = "Entity", def = "Relation::SelfRef1.def().rev()")]
    SelfRef1Reverse,
    #[sea_orm(entity = "super::link::Entity")]
    Link,
    #[sea_orm(entity = "super::link_type::Entity")]
    LinkType,
}
