//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "link_attribute_text_value")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub link: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub attribute_type: i32,
    #[sea_orm(column_type = "Text")]
    pub text_value: String,
}


#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
