//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "link_attribute_credit")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub link: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub attribute_type: i32,
    #[sea_orm(column_type = "Text")]
    pub credited_as: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::link::Entity",
        from = "Column::Link",
        to = "super::link::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Link,
    #[sea_orm(
        belongs_to = "super::link_creditable_attribute_type::Entity",
        from = "Column::AttributeType",
        to = "super::link_creditable_attribute_type::Column::AttributeType",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    LinkCreditableAttributeType,
}

impl Related<super::link::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Link.def()
    }
}

impl Related<super::link_creditable_attribute_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LinkCreditableAttributeType.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::link::Entity")]
    Link,
    #[sea_orm(entity = "super::link_creditable_attribute_type::Entity")]
    LinkCreditableAttributeType,
}
