//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "link_type_attribute_type")]
pub struct Model {
    #[sea_orm(
        belongs_to,
        from = "link_type",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction",
        primary_key,
        auto_increment = false
    )]
    pub link_type: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub attribute_type: i32,
    pub min: Option<i16>,
    pub max: Option<i16>,
    pub last_updated: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        from = "attribute_type",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub link_attribute_type: HasOne<super::link_attribute_type::Entity>,
    #[sea_orm(
        belongs_to,
        from = "link_type",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub link_type: HasOne<super::link_type::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
