//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "link_text_attribute_type")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub attribute_type: i32,
    #[sea_orm(
        belongs_to,
        from = "attribute_type",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub link_attribute_type: HasOne<super::link_attribute_type::Entity>,
    #[sea_orm(has_many, via = "link_attribute_text_value")]
    pub links: HasMany<super::link::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
