//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "medium_cdtoc")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub medium: i32,
    pub cdtoc: i32,
    pub edits_pending: i32,
    pub last_updated: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cdtoc::Entity",
        from = "Column::Cdtoc",
        to = "super::cdtoc::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Cdtoc,
    #[sea_orm(
        belongs_to = "super::medium::Entity",
        from = "Column::Medium",
        to = "super::medium::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Medium,
}

impl Related<super::cdtoc::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cdtoc.def()
    }
}

impl Related<super::medium::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Medium.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::cdtoc::Entity")]
    Cdtoc,
    #[sea_orm(entity = "super::medium::Entity")]
    Medium,
}
