//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "medium_attribute")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub medium: i32,
    pub medium_attribute_type: i32,
    pub medium_attribute_type_allowed_value: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub medium_attribute_text: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::medium::Entity",
        from = "Column::Medium",
        to = "super::medium::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Medium,
    #[sea_orm(
        belongs_to = "super::medium_attribute_type::Entity",
        from = "Column::MediumAttributeType",
        to = "super::medium_attribute_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MediumAttributeType,
    #[sea_orm(
        belongs_to = "super::medium_attribute_type_allowed_value::Entity",
        from = "Column::MediumAttributeTypeAllowedValue",
        to = "super::medium_attribute_type_allowed_value::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MediumAttributeTypeAllowedValue,
}

impl Related<super::medium::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Medium.def()
    }
}

impl Related<super::medium_attribute_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediumAttributeType.def()
    }
}

impl Related<super::medium_attribute_type_allowed_value::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediumAttributeTypeAllowedValue.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::medium::Entity")]
    Medium,
    #[sea_orm(entity = "super::medium_attribute_type::Entity")]
    MediumAttributeType,
    #[sea_orm(entity = "super::medium_attribute_type_allowed_value::Entity")]
    MediumAttributeTypeAllowedValue,
}
