//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "medium_format")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub parent: Option<i32>,
    pub child_order: i32,
    pub year: Option<i16>,
    pub has_discids: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(unique)]
    pub gid: Uuid,
    #[sea_orm(has_many)]
    pub mediums: HasMany<super::medium::Entity>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "parent",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub medium_format: HasOne<Entity>,
    #[sea_orm(has_many, via = "medium_attribute_type_allowed_format")]
    pub medium_attribute_types: HasMany<super::medium_attribute_type::Entity>,
    #[sea_orm(has_many, via = "medium_attribute_type_allowed_value_allowed_format")]
    pub medium_attribute_type_allowed_values:
        HasMany<super::medium_attribute_type_allowed_value::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
