//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(
    schema_name = "musicbrainz",
    table_name = "medium_attribute_type_allowed_format"
)]
pub struct Model {
    #[sea_orm(
        belongs_to,
        from = "medium_format",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction",
        primary_key,
        auto_increment = false
    )]
    pub medium_format: i32,
    #[sea_orm(
        belongs_to,
        from = "medium_attribute_type",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction",
        primary_key,
        auto_increment = false
    )]
    pub medium_attribute_type: i32,
    #[sea_orm(
        belongs_to,
        from = "medium_attribute_type",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub medium_attribute_type: HasOne<super::medium_attribute_type::Entity>,
    #[sea_orm(
        belongs_to,
        from = "medium_format",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub medium_format: HasOne<super::medium_format::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
