//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "medium_format")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub parent: Option<i32>,
    pub child_order: i32,
    pub year: Option<i16>,
    pub has_discids: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(unique)]
    pub gid: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::medium::Entity")]
    Medium,
    #[sea_orm(has_many = "super::medium_attribute_type_allowed_format::Entity")]
    MediumAttributeTypeAllowedFormat,
    #[sea_orm(has_many = "super::medium_attribute_type_allowed_value_allowed_format::Entity")]
    MediumAttributeTypeAllowedValueAllowedFormat,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::Parent",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
}

impl Related<super::medium::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Medium.def()
    }
}

impl Related<super::medium_attribute_type_allowed_format::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediumAttributeTypeAllowedFormat.def()
    }
}

impl Related<super::medium_attribute_type_allowed_value_allowed_format::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediumAttributeTypeAllowedValueAllowedFormat.def()
    }
}

impl Related<super::medium_attribute_type::Entity> for Entity {
    fn to() -> RelationDef {
        super::medium_attribute_type_allowed_format::Relation::MediumAttributeType.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::medium_attribute_type_allowed_format::Relation::MediumFormat
                .def()
                .rev(),
        )
    }
}

impl Related<super::medium_attribute_type_allowed_value::Entity> for Entity {
    fn to() -> RelationDef {
        super :: medium_attribute_type_allowed_value_allowed_format :: Relation :: MediumAttributeTypeAllowedValue . def ()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::medium_attribute_type_allowed_value_allowed_format::Relation::MediumFormat
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::medium::Entity")]
    Medium,
    #[sea_orm(entity = "super::medium_attribute_type_allowed_format::Entity")]
    MediumAttributeTypeAllowedFormat,
    #[sea_orm(entity = "super::medium_attribute_type_allowed_value_allowed_format::Entity")]
    MediumAttributeTypeAllowedValueAllowedFormat,
    #[sea_orm(entity = "Entity", def = "Relation::SelfRef.def()")]
    SelfRef,
    #[sea_orm(entity = "Entity", def = "Relation::SelfRef.def().rev()")]
    SelfRefReverse,
    #[sea_orm(entity = "super::medium_attribute_type::Entity")]
    MediumAttributeType,
    #[sea_orm(entity = "super::medium_attribute_type_allowed_value::Entity")]
    MediumAttributeTypeAllowedValue,
}
