//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "medium")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub release: i32,
    #[sea_orm(unique_key = "medium_uniq")]
    pub position: i32,
    pub format: Option<i32>,
    pub name: String,
    pub edits_pending: i32,
    pub last_updated: Option<DateTimeWithTimeZone>,
    pub track_count: i32,
    #[sea_orm(unique)]
    pub gid: Uuid,
}


impl ActiveModelBehavior for ActiveModel {}
