//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(
    table_name = "medium_attribute_type_allowed_value_allowed_format"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub medium_format: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub medium_attribute_type_allowed_value: i32,
}


impl ActiveModelBehavior for ActiveModel {}
