//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(
    schema_name = "musicbrainz",
    table_name = "medium_attribute_type_allowed_value_allowed_format"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub medium_format: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub medium_attribute_type_allowed_value: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::medium_attribute_type_allowed_value::Entity",
        from = "Column::MediumAttributeTypeAllowedValue",
        to = "super::medium_attribute_type_allowed_value::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MediumAttributeTypeAllowedValue,
    #[sea_orm(
        belongs_to = "super::medium_format::Entity",
        from = "Column::MediumFormat",
        to = "super::medium_format::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MediumFormat,
}

impl Related<super::medium_attribute_type_allowed_value::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediumAttributeTypeAllowedValue.def()
    }
}

impl Related<super::medium_format::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediumFormat.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::medium_attribute_type_allowed_value::Entity")]
    MediumAttributeTypeAllowedValue,
    #[sea_orm(entity = "super::medium_format::Entity")]
    MediumFormat,
}
