//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "mood")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub gid: Uuid,
    pub name: String,
    pub comment: String,
    pub edits_pending: i32,
    pub last_updated: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::edit_mood::Entity")]
    EditMood,
    #[sea_orm(has_many = "super::l_area_mood::Entity")]
    LAreaMood,
    #[sea_orm(has_many = "super::l_artist_mood::Entity")]
    LArtistMood,
    #[sea_orm(has_many = "super::l_event_mood::Entity")]
    LEventMood,
    #[sea_orm(has_many = "super::l_genre_mood::Entity")]
    LGenreMood,
    #[sea_orm(has_many = "super::l_instrument_mood::Entity")]
    LInstrumentMood,
    #[sea_orm(has_many = "super::l_label_mood::Entity")]
    LLabelMood,
    #[sea_orm(has_many = "super::l_mood_place::Entity")]
    LMoodPlace,
    #[sea_orm(has_many = "super::l_mood_recording::Entity")]
    LMoodRecording,
    #[sea_orm(has_many = "super::l_mood_release::Entity")]
    LMoodRelease,
    #[sea_orm(has_many = "super::l_mood_release_group::Entity")]
    LMoodReleaseGroup,
    #[sea_orm(has_many = "super::l_mood_series::Entity")]
    LMoodSeries,
    #[sea_orm(has_many = "super::l_mood_url::Entity")]
    LMoodUrl,
    #[sea_orm(has_many = "super::l_mood_work::Entity")]
    LMoodWork,
    #[sea_orm(has_many = "super::mood_alias::Entity")]
    MoodAlias,
    #[sea_orm(has_many = "super::mood_annotation::Entity")]
    MoodAnnotation,
}

impl Related<super::edit_mood::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditMood.def()
    }
}

impl Related<super::l_area_mood::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaMood.def()
    }
}

impl Related<super::l_artist_mood::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistMood.def()
    }
}

impl Related<super::l_event_mood::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LEventMood.def()
    }
}

impl Related<super::l_genre_mood::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LGenreMood.def()
    }
}

impl Related<super::l_instrument_mood::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LInstrumentMood.def()
    }
}

impl Related<super::l_label_mood::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LLabelMood.def()
    }
}

impl Related<super::l_mood_place::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LMoodPlace.def()
    }
}

impl Related<super::l_mood_recording::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LMoodRecording.def()
    }
}

impl Related<super::l_mood_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LMoodRelease.def()
    }
}

impl Related<super::l_mood_release_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LMoodReleaseGroup.def()
    }
}

impl Related<super::l_mood_series::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LMoodSeries.def()
    }
}

impl Related<super::l_mood_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LMoodUrl.def()
    }
}

impl Related<super::l_mood_work::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LMoodWork.def()
    }
}

impl Related<super::mood_alias::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MoodAlias.def()
    }
}

impl Related<super::mood_annotation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MoodAnnotation.def()
    }
}

impl Related<super::annotation::Entity> for Entity {
    fn to() -> RelationDef {
        super::mood_annotation::Relation::Annotation.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::mood_annotation::Relation::Mood.def().rev())
    }
}

impl Related<super::edit::Entity> for Entity {
    fn to() -> RelationDef {
        super::edit_mood::Relation::Edit.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::edit_mood::Relation::Mood.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::edit_mood::Entity")]
    EditMood,
    #[sea_orm(entity = "super::l_area_mood::Entity")]
    LAreaMood,
    #[sea_orm(entity = "super::l_artist_mood::Entity")]
    LArtistMood,
    #[sea_orm(entity = "super::l_event_mood::Entity")]
    LEventMood,
    #[sea_orm(entity = "super::l_genre_mood::Entity")]
    LGenreMood,
    #[sea_orm(entity = "super::l_instrument_mood::Entity")]
    LInstrumentMood,
    #[sea_orm(entity = "super::l_label_mood::Entity")]
    LLabelMood,
    #[sea_orm(entity = "super::l_mood_place::Entity")]
    LMoodPlace,
    #[sea_orm(entity = "super::l_mood_recording::Entity")]
    LMoodRecording,
    #[sea_orm(entity = "super::l_mood_release::Entity")]
    LMoodRelease,
    #[sea_orm(entity = "super::l_mood_release_group::Entity")]
    LMoodReleaseGroup,
    #[sea_orm(entity = "super::l_mood_series::Entity")]
    LMoodSeries,
    #[sea_orm(entity = "super::l_mood_url::Entity")]
    LMoodUrl,
    #[sea_orm(entity = "super::l_mood_work::Entity")]
    LMoodWork,
    #[sea_orm(entity = "super::mood_alias::Entity")]
    MoodAlias,
    #[sea_orm(entity = "super::mood_annotation::Entity")]
    MoodAnnotation,
    #[sea_orm(entity = "super::annotation::Entity")]
    Annotation,
    #[sea_orm(entity = "super::edit::Entity")]
    Edit,
}
