//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "orderable_link_type")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub link_type: i32,
    pub direction: i16,
}


impl ActiveModelBehavior for ActiveModel {}
