//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "place_alias")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub place: i32,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable, unique_key = "place_alias_idx_primary")]
    pub locale: Option<String>,
    pub edits_pending: i32,
    pub last_updated: Option<DateTimeWithTimeZone>,
    pub r#type: Option<i32>,
    pub sort_name: String,
    pub begin_date_year: Option<i16>,
    pub begin_date_month: Option<i16>,
    pub begin_date_day: Option<i16>,
    pub end_date_year: Option<i16>,
    pub end_date_month: Option<i16>,
    pub end_date_day: Option<i16>,
    pub primary_for_locale: bool,
    pub ended: bool,
}


#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
