//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "recording_tag_raw")]
pub struct Model {
    #[sea_orm(
        belongs_to,
        from = "recording",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction",
        primary_key,
        auto_increment = false
    )]
    pub recording: i32,
    #[sea_orm(
        belongs_to,
        from = "editor",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction",
        primary_key,
        auto_increment = false
    )]
    pub editor: i32,
    #[sea_orm(
        belongs_to,
        from = "tag",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction",
        primary_key,
        auto_increment = false
    )]
    pub tag: i32,
    pub is_upvote: bool,
    #[sea_orm(
        belongs_to,
        from = "editor",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub editor: HasOne<super::editor::Entity>,
    #[sea_orm(
        belongs_to,
        from = "recording",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub recording: HasOne<super::recording::Entity>,
    #[sea_orm(
        belongs_to,
        from = "tag",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub tag: HasOne<super::tag::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
