//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(
    schema_name = "musicbrainz",
    table_name = "recording_first_release_date"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub recording: i32,
    pub year: Option<i16>,
    pub month: Option<i16>,
    pub day: Option<i16>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::recording::Entity",
        from = "Column::Recording",
        to = "super::recording::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Recording,
}

impl Related<super::recording::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Recording.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::recording::Entity")]
    Recording,
}
