//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "recording_attribute")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub recording: i32,
    pub recording_attribute_type: i32,
    pub recording_attribute_type_allowed_value: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub recording_attribute_text: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::recording::Entity",
        from = "Column::Recording",
        to = "super::recording::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Recording,
    #[sea_orm(
        belongs_to = "super::recording_attribute_type::Entity",
        from = "Column::RecordingAttributeType",
        to = "super::recording_attribute_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    RecordingAttributeType,
    #[sea_orm(
        belongs_to = "super::recording_attribute_type_allowed_value::Entity",
        from = "Column::RecordingAttributeTypeAllowedValue",
        to = "super::recording_attribute_type_allowed_value::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    RecordingAttributeTypeAllowedValue,
}

impl Related<super::recording::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Recording.def()
    }
}

impl Related<super::recording_attribute_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecordingAttributeType.def()
    }
}

impl Related<super::recording_attribute_type_allowed_value::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecordingAttributeTypeAllowedValue.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::recording::Entity")]
    Recording,
    #[sea_orm(entity = "super::recording_attribute_type::Entity")]
    RecordingAttributeType,
    #[sea_orm(entity = "super::recording_attribute_type_allowed_value::Entity")]
    RecordingAttributeTypeAllowedValue,
}
