//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "recording")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub gid: Uuid,
    pub name: String,
    pub artist_credit: i32,
    pub length: Option<i32>,
    pub comment: String,
    pub edits_pending: i32,
    pub last_updated: Option<DateTimeWithTimeZone>,
    pub video: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::artist_credit::Entity",
        from = "Column::ArtistCredit",
        to = "super::artist_credit::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ArtistCredit,
    #[sea_orm(has_many = "super::edit_recording::Entity")]
    EditRecording,
    #[sea_orm(has_many = "super::editor_collection_recording::Entity")]
    EditorCollectionRecording,
    #[sea_orm(has_many = "super::isrc::Entity")]
    Isrc,
    #[sea_orm(has_many = "super::l_area_recording::Entity")]
    LAreaRecording,
    #[sea_orm(has_many = "super::l_artist_recording::Entity")]
    LArtistRecording,
    #[sea_orm(has_many = "super::l_event_recording::Entity")]
    LEventRecording,
    #[sea_orm(has_many = "super::l_genre_recording::Entity")]
    LGenreRecording,
    #[sea_orm(has_many = "super::l_instrument_recording::Entity")]
    LInstrumentRecording,
    #[sea_orm(has_many = "super::l_label_recording::Entity")]
    LLabelRecording,
    #[sea_orm(has_many = "super::l_mood_recording::Entity")]
    LMoodRecording,
    #[sea_orm(has_many = "super::l_place_recording::Entity")]
    LPlaceRecording,
    #[sea_orm(has_many = "super::l_recording_release::Entity")]
    LRecordingRelease,
    #[sea_orm(has_many = "super::l_recording_release_group::Entity")]
    LRecordingReleaseGroup,
    #[sea_orm(has_many = "super::l_recording_series::Entity")]
    LRecordingSeries,
    #[sea_orm(has_many = "super::l_recording_url::Entity")]
    LRecordingUrl,
    #[sea_orm(has_many = "super::l_recording_work::Entity")]
    LRecordingWork,
    #[sea_orm(has_many = "super::recording_alias::Entity")]
    RecordingAlias,
    #[sea_orm(has_many = "super::recording_annotation::Entity")]
    RecordingAnnotation,
    #[sea_orm(has_many = "super::recording_attribute::Entity")]
    RecordingAttribute,
    #[sea_orm(has_many = "super::recording_gid_redirect::Entity")]
    RecordingGidRedirect,
    #[sea_orm(has_one = "super::recording_meta::Entity")]
    RecordingMeta,
    #[sea_orm(has_many = "super::recording_rating_raw::Entity")]
    RecordingRatingRaw,
    #[sea_orm(has_many = "super::recording_tag::Entity")]
    RecordingTag,
    #[sea_orm(has_many = "super::recording_tag_raw::Entity")]
    RecordingTagRaw,
    #[sea_orm(has_many = "super::track::Entity")]
    Track,
}

impl Related<super::artist_credit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtistCredit.def()
    }
}

impl Related<super::edit_recording::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditRecording.def()
    }
}

impl Related<super::editor_collection_recording::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditorCollectionRecording.def()
    }
}

impl Related<super::isrc::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Isrc.def()
    }
}

impl Related<super::l_area_recording::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaRecording.def()
    }
}

impl Related<super::l_artist_recording::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistRecording.def()
    }
}

impl Related<super::l_event_recording::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LEventRecording.def()
    }
}

impl Related<super::l_genre_recording::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LGenreRecording.def()
    }
}

impl Related<super::l_instrument_recording::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LInstrumentRecording.def()
    }
}

impl Related<super::l_label_recording::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LLabelRecording.def()
    }
}

impl Related<super::l_mood_recording::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LMoodRecording.def()
    }
}

impl Related<super::l_place_recording::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LPlaceRecording.def()
    }
}

impl Related<super::l_recording_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LRecordingRelease.def()
    }
}

impl Related<super::l_recording_release_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LRecordingReleaseGroup.def()
    }
}

impl Related<super::l_recording_series::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LRecordingSeries.def()
    }
}

impl Related<super::l_recording_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LRecordingUrl.def()
    }
}

impl Related<super::l_recording_work::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LRecordingWork.def()
    }
}

impl Related<super::recording_alias::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecordingAlias.def()
    }
}

impl Related<super::recording_annotation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecordingAnnotation.def()
    }
}

impl Related<super::recording_attribute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecordingAttribute.def()
    }
}

impl Related<super::recording_gid_redirect::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecordingGidRedirect.def()
    }
}

impl Related<super::recording_meta::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecordingMeta.def()
    }
}

impl Related<super::recording_rating_raw::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecordingRatingRaw.def()
    }
}

impl Related<super::recording_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecordingTag.def()
    }
}

impl Related<super::recording_tag_raw::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecordingTagRaw.def()
    }
}

impl Related<super::track::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Track.def()
    }
}

impl Related<super::annotation::Entity> for Entity {
    fn to() -> RelationDef {
        super::recording_annotation::Relation::Annotation.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::recording_annotation::Relation::Recording.def().rev())
    }
}

impl Related<super::edit::Entity> for Entity {
    fn to() -> RelationDef {
        super::edit_recording::Relation::Edit.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::edit_recording::Relation::Recording.def().rev())
    }
}

impl Related<super::editor::Entity> for Entity {
    fn to() -> RelationDef {
        super::recording_rating_raw::Relation::Editor.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::recording_rating_raw::Relation::Recording.def().rev())
    }
}

impl Related<super::editor_collection::Entity> for Entity {
    fn to() -> RelationDef {
        super::editor_collection_recording::Relation::EditorCollection.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::editor_collection_recording::Relation::Recording
                .def()
                .rev(),
        )
    }
}

impl Related<super::tag::Entity> for Entity {
    fn to() -> RelationDef {
        super::recording_tag::Relation::Tag.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::recording_tag::Relation::Recording.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::artist_credit::Entity")]
    ArtistCredit,
    #[sea_orm(entity = "super::edit_recording::Entity")]
    EditRecording,
    #[sea_orm(entity = "super::editor_collection_recording::Entity")]
    EditorCollectionRecording,
    #[sea_orm(entity = "super::isrc::Entity")]
    Isrc,
    #[sea_orm(entity = "super::l_area_recording::Entity")]
    LAreaRecording,
    #[sea_orm(entity = "super::l_artist_recording::Entity")]
    LArtistRecording,
    #[sea_orm(entity = "super::l_event_recording::Entity")]
    LEventRecording,
    #[sea_orm(entity = "super::l_genre_recording::Entity")]
    LGenreRecording,
    #[sea_orm(entity = "super::l_instrument_recording::Entity")]
    LInstrumentRecording,
    #[sea_orm(entity = "super::l_label_recording::Entity")]
    LLabelRecording,
    #[sea_orm(entity = "super::l_mood_recording::Entity")]
    LMoodRecording,
    #[sea_orm(entity = "super::l_place_recording::Entity")]
    LPlaceRecording,
    #[sea_orm(entity = "super::l_recording_release::Entity")]
    LRecordingRelease,
    #[sea_orm(entity = "super::l_recording_release_group::Entity")]
    LRecordingReleaseGroup,
    #[sea_orm(entity = "super::l_recording_series::Entity")]
    LRecordingSeries,
    #[sea_orm(entity = "super::l_recording_url::Entity")]
    LRecordingUrl,
    #[sea_orm(entity = "super::l_recording_work::Entity")]
    LRecordingWork,
    #[sea_orm(entity = "super::recording_alias::Entity")]
    RecordingAlias,
    #[sea_orm(entity = "super::recording_annotation::Entity")]
    RecordingAnnotation,
    #[sea_orm(entity = "super::recording_attribute::Entity")]
    RecordingAttribute,
    #[sea_orm(entity = "super::recording_gid_redirect::Entity")]
    RecordingGidRedirect,
    #[sea_orm(entity = "super::recording_meta::Entity")]
    RecordingMeta,
    #[sea_orm(entity = "super::recording_rating_raw::Entity")]
    RecordingRatingRaw,
    #[sea_orm(entity = "super::recording_tag::Entity")]
    RecordingTag,
    #[sea_orm(entity = "super::recording_tag_raw::Entity")]
    RecordingTagRaw,
    #[sea_orm(entity = "super::track::Entity")]
    Track,
    #[sea_orm(entity = "super::annotation::Entity")]
    Annotation,
    #[sea_orm(entity = "super::edit::Entity")]
    Edit,
    #[sea_orm(entity = "super::editor::Entity")]
    Editor,
    #[sea_orm(entity = "super::editor_collection::Entity")]
    EditorCollection,
    #[sea_orm(entity = "super::tag::Entity")]
    Tag,
}
