//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(
    table_name = "recording_attribute_type_allowed_value"
)]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub recording_attribute_type: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub value: Option<String>,
    pub parent: Option<i32>,
    pub child_order: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(unique)]
    pub gid: Uuid,
}


impl ActiveModelBehavior for ActiveModel {}
