//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "recording_tag")]
pub struct Model {
    #[sea_orm(
        belongs_to,
        from = "recording",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction",
        primary_key,
        auto_increment = false
    )]
    pub recording: i32,
    #[sea_orm(
        belongs_to,
        from = "tag",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction",
        primary_key,
        auto_increment = false
    )]
    pub tag: i32,
    pub count: i32,
    pub last_updated: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        from = "recording",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub recording: HasOne<super::recording::Entity>,
    #[sea_orm(
        belongs_to,
        from = "tag",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub tag: HasOne<super::tag::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
