//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "release_attribute")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub release: i32,
    pub release_attribute_type: i32,
    pub release_attribute_type_allowed_value: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub release_attribute_text: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::release::Entity",
        from = "Column::Release",
        to = "super::release::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Release,
    #[sea_orm(
        belongs_to = "super::release_attribute_type::Entity",
        from = "Column::ReleaseAttributeType",
        to = "super::release_attribute_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ReleaseAttributeType,
    #[sea_orm(
        belongs_to = "super::release_attribute_type_allowed_value::Entity",
        from = "Column::ReleaseAttributeTypeAllowedValue",
        to = "super::release_attribute_type_allowed_value::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ReleaseAttributeTypeAllowedValue,
}

impl Related<super::release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Release.def()
    }
}

impl Related<super::release_attribute_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseAttributeType.def()
    }
}

impl Related<super::release_attribute_type_allowed_value::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseAttributeTypeAllowedValue.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::release::Entity")]
    Release,
    #[sea_orm(entity = "super::release_attribute_type::Entity")]
    ReleaseAttributeType,
    #[sea_orm(entity = "super::release_attribute_type_allowed_value::Entity")]
    ReleaseAttributeTypeAllowedValue,
}
