//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(
    schema_name = "musicbrainz",
    table_name = "release_group_secondary_type"
)]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub parent: Option<i32>,
    pub child_order: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(unique)]
    pub gid: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::Parent",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::release_group_secondary_type_join::Entity")]
    ReleaseGroupSecondaryTypeJoin,
}

impl Related<super::release_group_secondary_type_join::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseGroupSecondaryTypeJoin.def()
    }
}

impl Related<super::release_group::Entity> for Entity {
    fn to() -> RelationDef {
        super::release_group_secondary_type_join::Relation::ReleaseGroup.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::release_group_secondary_type_join::Relation::ReleaseGroupSecondaryType
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "Entity", def = "Relation::SelfRef.def()")]
    SelfRef,
    #[sea_orm(entity = "super::release_group_secondary_type_join::Entity")]
    ReleaseGroupSecondaryTypeJoin,
    #[sea_orm(entity = "Entity", def = "Relation::SelfRef.def().rev()")]
    SelfRefReverse,
    #[sea_orm(entity = "super::release_group::Entity")]
    ReleaseGroup,
}
