//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "release_raw")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub artist: Option<String>,
    pub added: Option<DateTimeWithTimeZone>,
    pub last_modified: Option<DateTimeWithTimeZone>,
    pub lookup_count: Option<i32>,
    pub modify_count: Option<i32>,
    pub source: Option<i32>,
    pub barcode: Option<String>,
    pub comment: String,
}


impl ActiveModelBehavior for ActiveModel {}
