//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "release")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub gid: Uuid,
    pub name: String,
    pub artist_credit: i32,
    pub release_group: i32,
    pub status: Option<i32>,
    pub packaging: Option<i32>,
    pub language: Option<i32>,
    pub script: Option<i32>,
    pub barcode: Option<String>,
    pub comment: String,
    pub edits_pending: i32,
    pub quality: i16,
    pub last_updated: Option<DateTimeWithTimeZone>,
}


#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
