//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "release_group_rating_raw")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub release_group: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub editor: i32,
    pub rating: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::editor::Entity",
        from = "Column::Editor",
        to = "super::editor::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Editor,
    #[sea_orm(
        belongs_to = "super::release_group::Entity",
        from = "Column::ReleaseGroup",
        to = "super::release_group::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ReleaseGroup,
}

impl Related<super::editor::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Editor.def()
    }
}

impl Related<super::release_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseGroup.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::editor::Entity")]
    Editor,
    #[sea_orm(entity = "super::release_group::Entity")]
    ReleaseGroup,
}
