//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "release_raw")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub artist: Option<String>,
    pub added: Option<DateTimeWithTimeZone>,
    pub last_modified: Option<DateTimeWithTimeZone>,
    pub lookup_count: Option<i32>,
    pub modify_count: Option<i32>,
    pub source: Option<i32>,
    pub barcode: Option<String>,
    pub comment: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cdtoc_raw::Entity")]
    CdtocRaw,
    #[sea_orm(has_many = "super::track_raw::Entity")]
    TrackRaw,
}

impl Related<super::cdtoc_raw::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CdtocRaw.def()
    }
}

impl Related<super::track_raw::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TrackRaw.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::cdtoc_raw::Entity")]
    CdtocRaw,
    #[sea_orm(entity = "super::track_raw::Entity")]
    TrackRaw,
}
