//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use super::sea_orm_active_enums::CoverArtPresence;
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "release_meta")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub date_added: Option<DateTimeWithTimeZone>,
    pub info_url: Option<String>,
    pub amazon_asin: Option<String>,
    pub cover_art_presence: CoverArtPresence,
    #[sea_orm(
        belongs_to,
        from = "id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub release: HasOne<super::release::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
