//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(
    schema_name = "musicbrainz",
    table_name = "release_attribute_type_allowed_value"
)]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub release_attribute_type: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub value: Option<String>,
    pub parent: Option<i32>,
    pub child_order: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(unique)]
    pub gid: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::release_attribute::Entity")]
    ReleaseAttribute,
    #[sea_orm(
        belongs_to = "super::release_attribute_type::Entity",
        from = "Column::ReleaseAttributeType",
        to = "super::release_attribute_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ReleaseAttributeType,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::Parent",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
}

impl Related<super::release_attribute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseAttribute.def()
    }
}

impl Related<super::release_attribute_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseAttributeType.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::release_attribute::Entity")]
    ReleaseAttribute,
    #[sea_orm(entity = "super::release_attribute_type::Entity")]
    ReleaseAttributeType,
    #[sea_orm(entity = "Entity", def = "Relation::SelfRef.def()")]
    SelfRef,
    #[sea_orm(entity = "Entity", def = "Relation::SelfRef.def().rev()")]
    SelfRefReverse,
}
