//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "release_label")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(
        belongs_to,
        from = "release",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub release: i32,
    #[sea_orm(
        belongs_to,
        from = "label",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub label: Option<i32>,
    pub catalog_number: Option<String>,
    pub last_updated: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        from = "label",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub label: HasOne<super::label::Entity>,
    #[sea_orm(
        belongs_to,
        from = "release",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub release: HasOne<super::release::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
