//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "release")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub gid: Uuid,
    pub name: String,
    pub artist_credit: i32,
    pub release_group: i32,
    pub status: Option<i32>,
    pub packaging: Option<i32>,
    pub language: Option<i32>,
    pub script: Option<i32>,
    pub barcode: Option<String>,
    pub comment: String,
    pub edits_pending: i32,
    pub quality: i16,
    pub last_updated: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::alternative_release::Entity")]
    AlternativeRelease,
    #[sea_orm(
        belongs_to = "super::artist_credit::Entity",
        from = "Column::ArtistCredit",
        to = "super::artist_credit::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ArtistCredit,
    #[sea_orm(has_many = "super::edit_release::Entity")]
    EditRelease,
    #[sea_orm(has_many = "super::editor_collection_release::Entity")]
    EditorCollectionRelease,
    #[sea_orm(has_many = "super::l_area_release::Entity")]
    LAreaRelease,
    #[sea_orm(has_many = "super::l_artist_release::Entity")]
    LArtistRelease,
    #[sea_orm(has_many = "super::l_event_release::Entity")]
    LEventRelease,
    #[sea_orm(has_many = "super::l_genre_release::Entity")]
    LGenreRelease,
    #[sea_orm(has_many = "super::l_instrument_release::Entity")]
    LInstrumentRelease,
    #[sea_orm(has_many = "super::l_label_release::Entity")]
    LLabelRelease,
    #[sea_orm(has_many = "super::l_mood_release::Entity")]
    LMoodRelease,
    #[sea_orm(has_many = "super::l_place_release::Entity")]
    LPlaceRelease,
    #[sea_orm(has_many = "super::l_recording_release::Entity")]
    LRecordingRelease,
    #[sea_orm(has_many = "super::l_release_release_group::Entity")]
    LReleaseReleaseGroup,
    #[sea_orm(has_many = "super::l_release_series::Entity")]
    LReleaseSeries,
    #[sea_orm(has_many = "super::l_release_url::Entity")]
    LReleaseUrl,
    #[sea_orm(has_many = "super::l_release_work::Entity")]
    LReleaseWork,
    #[sea_orm(
        belongs_to = "super::language::Entity",
        from = "Column::Language",
        to = "super::language::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Language,
    #[sea_orm(has_many = "super::medium::Entity")]
    Medium,
    #[sea_orm(has_many = "super::release_alias::Entity")]
    ReleaseAlias,
    #[sea_orm(has_many = "super::release_annotation::Entity")]
    ReleaseAnnotation,
    #[sea_orm(has_many = "super::release_attribute::Entity")]
    ReleaseAttribute,
    #[sea_orm(has_many = "super::release_country::Entity")]
    ReleaseCountry,
    #[sea_orm(has_many = "super::release_gid_redirect::Entity")]
    ReleaseGidRedirect,
    #[sea_orm(
        belongs_to = "super::release_group::Entity",
        from = "Column::ReleaseGroup",
        to = "super::release_group::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ReleaseGroup,
    #[sea_orm(has_many = "super::release_label::Entity")]
    ReleaseLabel,
    #[sea_orm(has_one = "super::release_meta::Entity")]
    ReleaseMeta,
    #[sea_orm(
        belongs_to = "super::release_packaging::Entity",
        from = "Column::Packaging",
        to = "super::release_packaging::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ReleasePackaging,
    #[sea_orm(
        belongs_to = "super::release_status::Entity",
        from = "Column::Status",
        to = "super::release_status::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ReleaseStatus,
    #[sea_orm(has_many = "super::release_tag::Entity")]
    ReleaseTag,
    #[sea_orm(has_many = "super::release_tag_raw::Entity")]
    ReleaseTagRaw,
    #[sea_orm(has_one = "super::release_unknown_country::Entity")]
    ReleaseUnknownCountry,
    #[sea_orm(
        belongs_to = "super::script::Entity",
        from = "Column::Script",
        to = "super::script::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Script,
}

impl Related<super::alternative_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlternativeRelease.def()
    }
}

impl Related<super::artist_credit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtistCredit.def()
    }
}

impl Related<super::edit_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditRelease.def()
    }
}

impl Related<super::editor_collection_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditorCollectionRelease.def()
    }
}

impl Related<super::l_area_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaRelease.def()
    }
}

impl Related<super::l_artist_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistRelease.def()
    }
}

impl Related<super::l_event_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LEventRelease.def()
    }
}

impl Related<super::l_genre_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LGenreRelease.def()
    }
}

impl Related<super::l_instrument_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LInstrumentRelease.def()
    }
}

impl Related<super::l_label_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LLabelRelease.def()
    }
}

impl Related<super::l_mood_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LMoodRelease.def()
    }
}

impl Related<super::l_place_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LPlaceRelease.def()
    }
}

impl Related<super::l_recording_release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LRecordingRelease.def()
    }
}

impl Related<super::l_release_release_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LReleaseReleaseGroup.def()
    }
}

impl Related<super::l_release_series::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LReleaseSeries.def()
    }
}

impl Related<super::l_release_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LReleaseUrl.def()
    }
}

impl Related<super::l_release_work::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LReleaseWork.def()
    }
}

impl Related<super::language::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Language.def()
    }
}

impl Related<super::medium::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Medium.def()
    }
}

impl Related<super::release_alias::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseAlias.def()
    }
}

impl Related<super::release_annotation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseAnnotation.def()
    }
}

impl Related<super::release_attribute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseAttribute.def()
    }
}

impl Related<super::release_country::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseCountry.def()
    }
}

impl Related<super::release_gid_redirect::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseGidRedirect.def()
    }
}

impl Related<super::release_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseGroup.def()
    }
}

impl Related<super::release_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseLabel.def()
    }
}

impl Related<super::release_meta::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseMeta.def()
    }
}

impl Related<super::release_packaging::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleasePackaging.def()
    }
}

impl Related<super::release_status::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseStatus.def()
    }
}

impl Related<super::release_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseTag.def()
    }
}

impl Related<super::release_tag_raw::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseTagRaw.def()
    }
}

impl Related<super::release_unknown_country::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseUnknownCountry.def()
    }
}

impl Related<super::script::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Script.def()
    }
}

impl Related<super::annotation::Entity> for Entity {
    fn to() -> RelationDef {
        super::release_annotation::Relation::Annotation.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::release_annotation::Relation::Release.def().rev())
    }
}

impl Related<super::country_area::Entity> for Entity {
    fn to() -> RelationDef {
        super::release_country::Relation::CountryArea.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::release_country::Relation::Release.def().rev())
    }
}

impl Related<super::edit::Entity> for Entity {
    fn to() -> RelationDef {
        super::edit_release::Relation::Edit.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::edit_release::Relation::Release.def().rev())
    }
}

impl Related<super::editor_collection::Entity> for Entity {
    fn to() -> RelationDef {
        super::editor_collection_release::Relation::EditorCollection.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::editor_collection_release::Relation::Release
                .def()
                .rev(),
        )
    }
}

impl Related<super::tag::Entity> for Entity {
    fn to() -> RelationDef {
        super::release_tag::Relation::Tag.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::release_tag::Relation::Release.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::alternative_release::Entity")]
    AlternativeRelease,
    #[sea_orm(entity = "super::artist_credit::Entity")]
    ArtistCredit,
    #[sea_orm(entity = "super::edit_release::Entity")]
    EditRelease,
    #[sea_orm(entity = "super::editor_collection_release::Entity")]
    EditorCollectionRelease,
    #[sea_orm(entity = "super::l_area_release::Entity")]
    LAreaRelease,
    #[sea_orm(entity = "super::l_artist_release::Entity")]
    LArtistRelease,
    #[sea_orm(entity = "super::l_event_release::Entity")]
    LEventRelease,
    #[sea_orm(entity = "super::l_genre_release::Entity")]
    LGenreRelease,
    #[sea_orm(entity = "super::l_instrument_release::Entity")]
    LInstrumentRelease,
    #[sea_orm(entity = "super::l_label_release::Entity")]
    LLabelRelease,
    #[sea_orm(entity = "super::l_mood_release::Entity")]
    LMoodRelease,
    #[sea_orm(entity = "super::l_place_release::Entity")]
    LPlaceRelease,
    #[sea_orm(entity = "super::l_recording_release::Entity")]
    LRecordingRelease,
    #[sea_orm(entity = "super::l_release_release_group::Entity")]
    LReleaseReleaseGroup,
    #[sea_orm(entity = "super::l_release_series::Entity")]
    LReleaseSeries,
    #[sea_orm(entity = "super::l_release_url::Entity")]
    LReleaseUrl,
    #[sea_orm(entity = "super::l_release_work::Entity")]
    LReleaseWork,
    #[sea_orm(entity = "super::language::Entity")]
    Language,
    #[sea_orm(entity = "super::medium::Entity")]
    Medium,
    #[sea_orm(entity = "super::release_alias::Entity")]
    ReleaseAlias,
    #[sea_orm(entity = "super::release_annotation::Entity")]
    ReleaseAnnotation,
    #[sea_orm(entity = "super::release_attribute::Entity")]
    ReleaseAttribute,
    #[sea_orm(entity = "super::release_country::Entity")]
    ReleaseCountry,
    #[sea_orm(entity = "super::release_gid_redirect::Entity")]
    ReleaseGidRedirect,
    #[sea_orm(entity = "super::release_group::Entity")]
    ReleaseGroup,
    #[sea_orm(entity = "super::release_label::Entity")]
    ReleaseLabel,
    #[sea_orm(entity = "super::release_meta::Entity")]
    ReleaseMeta,
    #[sea_orm(entity = "super::release_packaging::Entity")]
    ReleasePackaging,
    #[sea_orm(entity = "super::release_status::Entity")]
    ReleaseStatus,
    #[sea_orm(entity = "super::release_tag::Entity")]
    ReleaseTag,
    #[sea_orm(entity = "super::release_tag_raw::Entity")]
    ReleaseTagRaw,
    #[sea_orm(entity = "super::release_unknown_country::Entity")]
    ReleaseUnknownCountry,
    #[sea_orm(entity = "super::script::Entity")]
    Script,
    #[sea_orm(entity = "super::annotation::Entity")]
    Annotation,
    #[sea_orm(entity = "super::country_area::Entity")]
    CountryArea,
    #[sea_orm(entity = "super::edit::Entity")]
    Edit,
    #[sea_orm(entity = "super::editor_collection::Entity")]
    EditorCollection,
    #[sea_orm(entity = "super::tag::Entity")]
    Tag,
}
