//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "release_group_rating_raw")]
pub struct Model {
    #[sea_orm(
        belongs_to,
        from = "release_group",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction",
        primary_key,
        auto_increment = false
    )]
    pub release_group: i32,
    #[sea_orm(
        belongs_to,
        from = "editor",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction",
        primary_key,
        auto_increment = false
    )]
    pub editor: i32,
    pub rating: i16,
    #[sea_orm(
        belongs_to,
        from = "editor",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub editor: HasOne<super::editor::Entity>,
    #[sea_orm(
        belongs_to,
        from = "release_group",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub release_group: HasOne<super::release_group::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
