//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "cover_art_presence")]
pub enum CoverArtPresence {
    #[sea_orm(string_value = "absent")]
    Absent,
    #[sea_orm(string_value = "present")]
    Present,
    #[sea_orm(string_value = "darkened")]
    Darkened,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "edit_note_status")]
pub enum EditNoteStatus {
    #[sea_orm(string_value = "deleted")]
    Deleted,
    #[sea_orm(string_value = "edited")]
    Edited,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "event_art_presence")]
pub enum EventArtPresence {
    #[sea_orm(string_value = "absent")]
    Absent,
    #[sea_orm(string_value = "present")]
    Present,
    #[sea_orm(string_value = "darkened")]
    Darkened,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "fluency")]
pub enum Fluency {
    #[sea_orm(string_value = "basic")]
    Basic,
    #[sea_orm(string_value = "intermediate")]
    Intermediate,
    #[sea_orm(string_value = "advanced")]
    Advanced,
    #[sea_orm(string_value = "native")]
    Native,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "oauth_code_challenge_method"
)]
pub enum OauthCodeChallengeMethod {
    #[sea_orm(string_value = "plain")]
    Plain,
    #[sea_orm(string_value = "S256")]
    S256,
}
