//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tag_relation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub tag1: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub tag2: i32,
    pub weight: i32,
    pub last_updated: Option<DateTimeWithTimeZone>,
}


impl ActiveModelBehavior for ActiveModel {}
