//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "tag_relation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub tag1: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub tag2: i32,
    pub weight: i32,
    pub last_updated: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tag::Entity",
        from = "Column::Tag1",
        to = "super::tag::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Tag2,
    #[sea_orm(
        belongs_to = "super::tag::Entity",
        from = "Column::Tag2",
        to = "super::tag::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Tag1,
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::tag::Entity", def = "Relation::Tag2.def()")]
    Tag2,
    #[sea_orm(entity = "super::tag::Entity", def = "Relation::Tag1.def()")]
    Tag1,
}
