//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "track_gid_redirect")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub gid: Uuid,
    pub new_id: i32,
    pub created: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        from = "new_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub track: HasOne<super::track::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
