//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "track_raw")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub release: i32,
    pub title: String,
    pub artist: Option<String>,
    pub sequence: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::release_raw::Entity",
        from = "Column::Release",
        to = "super::release_raw::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ReleaseRaw,
}

impl Related<super::release_raw::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseRaw.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::release_raw::Entity")]
    ReleaseRaw,
}
