//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "unreferenced_row_log")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub table_name: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub row_id: i32,
    pub inserted: Option<DateTimeWithTimeZone>,
}


impl ActiveModelBehavior for ActiveModel {}
