//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "url")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub gid: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub url: String,
    pub edits_pending: i32,
    pub last_updated: Option<DateTimeWithTimeZone>,
}


impl ActiveModelBehavior for ActiveModel {}
