//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "url")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub gid: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub url: String,
    pub edits_pending: i32,
    pub last_updated: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::edit_url::Entity")]
    EditUrl,
    #[sea_orm(has_many = "super::l_area_url::Entity")]
    LAreaUrl,
    #[sea_orm(has_many = "super::l_artist_url::Entity")]
    LArtistUrl,
    #[sea_orm(has_many = "super::l_event_url::Entity")]
    LEventUrl,
    #[sea_orm(has_many = "super::l_genre_url::Entity")]
    LGenreUrl,
    #[sea_orm(has_many = "super::l_instrument_url::Entity")]
    LInstrumentUrl,
    #[sea_orm(has_many = "super::l_label_url::Entity")]
    LLabelUrl,
    #[sea_orm(has_many = "super::l_mood_url::Entity")]
    LMoodUrl,
    #[sea_orm(has_many = "super::l_place_url::Entity")]
    LPlaceUrl,
    #[sea_orm(has_many = "super::l_recording_url::Entity")]
    LRecordingUrl,
    #[sea_orm(has_many = "super::l_release_group_url::Entity")]
    LReleaseGroupUrl,
    #[sea_orm(has_many = "super::l_release_url::Entity")]
    LReleaseUrl,
    #[sea_orm(has_many = "super::l_series_url::Entity")]
    LSeriesUrl,
    #[sea_orm(has_many = "super::l_url_work::Entity")]
    LUrlWork,
    #[sea_orm(has_many = "super::url_gid_redirect::Entity")]
    UrlGidRedirect,
}

impl Related<super::edit_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditUrl.def()
    }
}

impl Related<super::l_area_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LAreaUrl.def()
    }
}

impl Related<super::l_artist_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LArtistUrl.def()
    }
}

impl Related<super::l_event_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LEventUrl.def()
    }
}

impl Related<super::l_genre_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LGenreUrl.def()
    }
}

impl Related<super::l_instrument_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LInstrumentUrl.def()
    }
}

impl Related<super::l_label_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LLabelUrl.def()
    }
}

impl Related<super::l_mood_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LMoodUrl.def()
    }
}

impl Related<super::l_place_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LPlaceUrl.def()
    }
}

impl Related<super::l_recording_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LRecordingUrl.def()
    }
}

impl Related<super::l_release_group_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LReleaseGroupUrl.def()
    }
}

impl Related<super::l_release_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LReleaseUrl.def()
    }
}

impl Related<super::l_series_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LSeriesUrl.def()
    }
}

impl Related<super::l_url_work::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LUrlWork.def()
    }
}

impl Related<super::url_gid_redirect::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UrlGidRedirect.def()
    }
}

impl Related<super::edit::Entity> for Entity {
    fn to() -> RelationDef {
        super::edit_url::Relation::Edit.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::edit_url::Relation::Url.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::edit_url::Entity")]
    EditUrl,
    #[sea_orm(entity = "super::l_area_url::Entity")]
    LAreaUrl,
    #[sea_orm(entity = "super::l_artist_url::Entity")]
    LArtistUrl,
    #[sea_orm(entity = "super::l_event_url::Entity")]
    LEventUrl,
    #[sea_orm(entity = "super::l_genre_url::Entity")]
    LGenreUrl,
    #[sea_orm(entity = "super::l_instrument_url::Entity")]
    LInstrumentUrl,
    #[sea_orm(entity = "super::l_label_url::Entity")]
    LLabelUrl,
    #[sea_orm(entity = "super::l_mood_url::Entity")]
    LMoodUrl,
    #[sea_orm(entity = "super::l_place_url::Entity")]
    LPlaceUrl,
    #[sea_orm(entity = "super::l_recording_url::Entity")]
    LRecordingUrl,
    #[sea_orm(entity = "super::l_release_group_url::Entity")]
    LReleaseGroupUrl,
    #[sea_orm(entity = "super::l_release_url::Entity")]
    LReleaseUrl,
    #[sea_orm(entity = "super::l_series_url::Entity")]
    LSeriesUrl,
    #[sea_orm(entity = "super::l_url_work::Entity")]
    LUrlWork,
    #[sea_orm(entity = "super::url_gid_redirect::Entity")]
    UrlGidRedirect,
    #[sea_orm(entity = "super::edit::Entity")]
    Edit,
}
