//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "vote")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(
        belongs_to,
        from = "editor",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub editor: i32,
    #[sea_orm(
        belongs_to,
        from = "edit",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub edit: i32,
    pub vote: i16,
    pub vote_time: Option<DateTimeWithTimeZone>,
    pub superseded: bool,
    #[sea_orm(
        belongs_to,
        from = "edit",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub edit: HasOne<super::edit::Entity>,
    #[sea_orm(
        belongs_to,
        from = "editor",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub editor: HasOne<super::editor::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
