//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "work_language")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub work: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub language: i32,
    pub edits_pending: i32,
    pub created: Option<DateTimeWithTimeZone>,
}


#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
