//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "work_attribute")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub work: i32,
    pub work_attribute_type: i32,
    pub work_attribute_type_allowed_value: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub work_attribute_text: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::work::Entity",
        from = "Column::Work",
        to = "super::work::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Work,
    #[sea_orm(
        belongs_to = "super::work_attribute_type::Entity",
        from = "Column::WorkAttributeType",
        to = "super::work_attribute_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    WorkAttributeType,
    #[sea_orm(
        belongs_to = "super::work_attribute_type_allowed_value::Entity",
        from = "Column::WorkAttributeTypeAllowedValue",
        to = "super::work_attribute_type_allowed_value::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    WorkAttributeTypeAllowedValue,
}

impl Related<super::work::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Work.def()
    }
}

impl Related<super::work_attribute_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkAttributeType.def()
    }
}

impl Related<super::work_attribute_type_allowed_value::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkAttributeTypeAllowedValue.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::work::Entity")]
    Work,
    #[sea_orm(entity = "super::work_attribute_type::Entity")]
    WorkAttributeType,
    #[sea_orm(entity = "super::work_attribute_type_allowed_value::Entity")]
    WorkAttributeTypeAllowedValue,
}
