//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "work_tag")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub work: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub tag: i32,
    pub count: i32,
    pub last_updated: Option<DateTimeWithTimeZone>,
}


impl ActiveModelBehavior for ActiveModel {}
