//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "musicbrainz", table_name = "work_language")]
pub struct Model {
    #[sea_orm(
        belongs_to,
        from = "work",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction",
        primary_key,
        auto_increment = false
    )]
    pub work: i32,
    #[sea_orm(
        belongs_to,
        from = "language",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction",
        primary_key,
        auto_increment = false
    )]
    pub language: i32,
    pub edits_pending: i32,
    pub created: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        from = "language",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub language: HasOne<super::language::Entity>,
    #[sea_orm(
        belongs_to,
        from = "work",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub work: HasOne<super::work::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
